pactus-project/pactus

Makefile, go.mod, version/version.go
- Tagged as V1.0.1
- `git tag 1.0.1` will update version automaticly
- ```-ldflags "-X github.com/zarbchain/zarb-go/version.GitCommit=`git rev-parse --short=8 HEAD`"``` flag added to make file
=> add SemVersion Support via Git Tags

consensus/consensus.go, consensus/height_test.go, consensus/precommit_test.go, consensus/prepare.go, consensus/prepare_test.go, consensus/propose_test.go, state/last_info/last_info.go, state/last_info/last_info_test.go, state/state.go, sync/sync.go
- Prevent sending proposal request on entering prepare stage
- Prevent re-scheduling new height timer
- Make sure committee members are valid on restarting the node
=> Don't ask for proposal on entering prepare stage

network/address.go, network/bootstrap.go, network/kademlia.go, network/mdns.go, network/network.go, network/topics.go
Add lp2p prefix to libp2p package names
=> Update libp2p package names

network/mock.go, sync/handler_aleyk.go, sync/handler_aleyk_test.go, sync/handler_salam.go, sync/handler_salam_test.go, sync/message/messages.go, sync/message/payload/aleyk.go, sync/message/payload/aleyk_test.go, sync/peerset/peer.go, sync/peerset/session.go, sync/sync.go, www/http/blockchain.go
Target Peer ID is added to Alyek messages. Other peers can eavesdrop the message to update the peer information.
=> p2p: Add responseTarget to Aleyk message

consensus/prepare_test.go
The `TestByzantineVote1` failed in slow containers like MacOS github action rarely.
This PR straightens this test
=> Test: Strengthening a test for consensus in slow environments

consensus/consensus.go, consensus/consensus_test.go
There is a random panic on starting the node. It is caused by picking a random vote. Since the round is set to `-1`, then `round+1` is zero, the random function sets the max to `MaxInt16`. By this change the round set to zero then the random vote will be picked between zero and one, which ultimately is a nil vote.
=> Set round to zero on constructing consensus

network/network.go, network/network_test.go
Check if `EnableNATService` set to zero and enable NAT service in libp2p
=> Enable NAT Service

cmd/zarbd/init.go, crypto/bls/private_key.go, crypto/bls/private_key_test.go, keystore/key/key.go
- Adding `keyInfo` parameter for `KeyGen` function, Default is nil.
- Make sure the SecretKey is always 32 bytes
=> Adding key info for keygen

.github/releasers/macos/Info.plist, .github/releasers/macos/gui.bundle, .github/releasers/releaser_macos.sh, .github/workflows/releaser.yml
With this MR zarb-go repo could generate a dmg file with all of its dependencies installed using Github actions and workflow. it will enable users to install and run zarb-gui with one click.
=> Update release workflow to support macos dmg installer

tests/main_test.go, wallet/vault/vault.go, wallet/vault/vault_test.go, wallet/wallet.go, wallet/wallet_test.go
`KeyInfo` for test net set to 1 to generate different key per network
=> Generating different key for testnet

execution/execution_test.go, execution/executor/bond.go, execution/executor/bond_test.go
For known validators public key should not set again in Bond transactions
Fixing #367
=> Check if public key is set in bond transactions

state/mock.go, sync/bundle/message/blocks_request.go, sync/bundle/message/blocks_request_test.go, sync/bundle/message/heart_beat.go, sync/bundle/message/heart_beat_test.go, sync/cache/cache.go, sync/handler_block_announce_test.go, sync/handler_blocks_request.go, sync/handler_blocks_request_test.go, sync/handler_heart_beat.go, sync/peerset/peer_set.go, sync/sync.go
Peer height wrongly set to 0xffffffff. This caused a critical issue in the sync module. In this PR I updated the height more accurately and ignored messages with height zero. Tests are added to cover the changes.
=> Updating peer height

consensus/mock.go, sync/bundle/message/query_proposal.go, sync/sync.go, sync/sync_test.go
Starting the consensus if the node is sync with the network. A test is added to cover this special case.
=> Starting the consensus if the node is sync with the network

node/node.go
Make sure the event channel is set to nil when the nanomsg is disabled. Otherwise after some blocks the channel becomes full and the node hangs.
=> Nil event channel if nanomsg is disabled

cmd/gtk/main.go
Starting the node on new thread for GUI app 
Sometimes GUI app in Windows shows not responding message.
=> gui: start node on new os thread

.github/releasers/releaser_gui_windows.sh
fixing missed dll in windows releaser:
`cp: cannot stat 'libpcre-1.dll': No such file or directory`
=> fixing missed dll in windows releaser

cmd/daemon/start.go, cmd/wallet/address.go, cmd/wallet/create.go, cmd/wallet/main.go, cmd/wallet/recover.go, cmd/wallet/tx.go, node/node.go, wallet/wallet.go
Adding server option to wallet commands. Now users can specify to which server they want to connect.
=> cli-wallet: adding server option

go.mod, go.sum
For some reason the old version is no longer a valid version.
See commit message.
If this PR closes any issue, mention here.
=> Upgrade go-libp2p-kad-dht module to v0.18.0

sortition/proof.go, sortition/sortition_test.go, sortition/vrf.go, sortition/vrf_test.go
Updating denominator fro the VRF to 2^256.
=> fix: using 2^256 for the vrf denominator

execution/execution.go, types/genesis/genesis_test.go, types/param/param.go, util/slice.go, util/slice_test.go
A new parameter added for the sortition interval.
- [ x] Breaking change (fix or feature that would cause existing functionality to change)
=> fix: adding sortition interval to the parameters

committee/committee.go, committee/committee_test.go, consensus/commit.go, consensus/consensus_test.go, consensus/height.go, consensus/manager.go, consensus/mediator.go, consensus/mock.go, consensus/prepare.go, state/state.go, sync/sync_test.go
Prevent data race conditions in committee by cloning validators.
This commit addresses a potential data race condition that can occur when a validator inside the committee updates. To prevent this, we now clone validators. This ensures that the original validators are not modified and eliminates the possibility of data race conditions.
=> fix: prevent data race conditions in committee 

consensus/consensus.go, consensus/consensus_test.go, consensus/log/log.go
This commit adds a check to ensure that votes with round numbers more than two rounds larger than the current round are rejected. This prevents byzantine validators from causing network crashes by broadcasting votes with large round numbers.
Fixing #465
=> fix(consensus): rejecting vote with round numbers exceeding the limit

wallet/encrypter/encrypter.go
The Argon2d parameters changed to consume less memory. This specially fix the allocation failure in the clouding platforms with memory less than 2 GB.
> If much less memory is available, a uniformly safe option is Argon2id with t=3 iterations, p=4 lanes, m=2^(16) (64 MiB of RAM), 128-bit salt, and 256-bit tag size. This is the SECOND RECOMMENDED option.
=> fix: reducing the default Argon2d to consume less memory

Dockerfile
alpine 1.16 supports go 1.18 causing this error: https://github.com/pactus-project/pactus/actions/runs/5046027649/jobs/9051025182
=> chore: updating alpine to support go1.20

cmd/gtk/assets/ui/widget_node.ui, cmd/gtk/icons.go, cmd/gtk/widget_node.go
Showing the total number of validators on the Main Window
=> feat(gui): showing the total number of validators

cmd/cmd.go, config/config.go, config/config_test.go
This pull request fixes the issue with restoring the configuration file to the default values when unable to load the config.
Related to #478
=> fix: restoring config file to the default

consensus/manager_test.go, sync/firewall/firewall_test.go, sync/sync.go
Sometimes, the relay connection encounters errors and gets closed. In such cases, we have increased the 'Send Filed' counter to track the connectivity.
=> fix: increase failed counter when stream encounters errors

cmd/cmd.go, cmd/daemon/init.go, cmd/gtk/main.go, config/config.go, config/config_test.go, docs/install.md, genesis/genesis.go, wallet/wallet.go
Supporting running localnet for development purpose.
=> fix: supporting localnet

Makefile, cmd/daemon/start.go, sync/bundle/bundle_test.go, sync/bundle/message/blocks_response.go, sync/bundle/message/blocks_response_test.go, sync/cache/cache.go, sync/cache/cache_test.go, sync/handler_blocks_request.go, sync/handler_blocks_response.go, sync/handler_blocks_response_test.go, sync/sync.go
This PR removes the `state` instance from the `cache` in the `sync` package. 
Additionally, the block data is now directly passed to the `block_response` message without parsing the block, which is expected to improve the performance of the node when processing the `block_request` messages.
=> fix: removing state from cache

network/mdns.go, network/mdns_test.go, network/network.go, network/network_test.go
The mDNS service was not closed after stopping the network. This PR addresses this issue by implementing the necessary closure. Additionally, it aims to resolve a random test failure that occurs in GitHub Actions, particularly on Windows. An example of such failure can be found at: https://github.com/pactus-project/pactus/actions/runs/5255419093/jobs/9495309402
=> fix: closing the mDNS connection upon stopping the network

execution/execution.go, sandbox/interface.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, store/account.go, store/block.go, store/interface.go, store/mock.go, store/store.go, store/store_test.go
This PR makes it possible to fetch the latest block using the stamp, which removes the need to search the levelDB for the specific block. 
This improve the performance of executing sortition transactions that need to obtain the sortition seeds based on the block stamp.
=> fix: get recent blocks by stamp

execution/executor/sortition.go, execution/executor/sortition_test.go, sandbox/interface.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, state/state.go, store/account.go, store/account_test.go, store/store.go, store/store_test.go, store/validator.go, store/validator_test.go, types/account/account.go, types/account/account_test.go, types/validator/validator.go, types/validator/validator_test.go
The primary objective of this PR is to enhance the performance of the software and it also aims to reduce the syncing time. Executing each transaction requires fetching the corresponding account or validator information from LevelDB. Since database read/write operations are costly, they can significantly impact performance.
To mitigate this, we've implemented caching for accounts and validators based on their addresses. This approach allows us to write data into the DB, while reading account or validator information is performed from the cached data.
Since we are utilizing a map for caching, the complexity of fetching data is `O(1)`, which ensures optimal performance. However, if the number of accounts becomes large, for example more than 1 million, we may need to use an LRU cache. …
=> fix: caching account and validator in store

execution/execution_test.go, execution/executor/bond.go, execution/executor/bond_test.go, execution/executor/sortition_test.go, execution/executor/unbond.go, execution/executor/unbond_test.go, sandbox/interface.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, state/state.go, state/state_test.go, txpool/pool_test.go
Prior to this PR, the total power (the total staked coins) was calculated at each height by iterating over all validators and summing up the power (stakes). This was not an efficient method for calculating total power.
With this PR, a more efficient approach has been implemented. Now, whenever a validator bonds or unbonds a stake, we record this as a power delta (change) and apply it to the total power. This removes the need for iterating over all validators at every height, thereby optimizing the total power calculation process.
=> refactor: optimization of total power calculation

cmd/gtk/main_window.go, cmd/gtk/startup_assistant.go, cmd/gtk/utils.go, util/utils.go, util/utils_test.go
This PR enables users to restore the `default_wallet` in the GUI within the initialize assistant dialog. 
To ensure proper page navigation, it jumps between pages based on the initialize mode.
Fixed #522 and #551
=> fix: implemented restore wallet base on input seed

.github/releasers/releaser_cli.sh, .github/releasers/releaser_gui_linux.sh, .github/releasers/releaser_gui_macos.sh, .github/releasers/releaser_gui_windows.sh
Set `CGO_ENABLED=0` to statically link the release binaries. 
It makes the application more portable without any dependencies.
It should address #545
=> chore: statically link release binaries

sync/handler.go, sync/handler_block_announce.go, sync/handler_blocks_request.go, sync/handler_blocks_response.go, sync/handler_heart_beat.go, sync/handler_hello.go, sync/handler_proposal.go, sync/handler_query_proposal.go, sync/handler_query_votes.go, sync/handler_transactions.go, sync/handler_vote.go, sync/sync.go
there was a typo about ParsMessage in messageHandler interface which I've fixed and converted to ParseMessage
=> style: rename ParsMessage to ParseMessage

www/http/server.go
the route for getValidatorByNumber is using getAccountByNumber handler
I just fixed it!
=> fix: incorrect handler for validator by number

www/grpc/grpc-gateway.config.yaml
add the missing API `GetAccountByNumber` in grpc-gateway.config.yaml
#527
=> fix: missing swagger ui for grpc get account by number

consensus/consensus_test.go, consensus/voteset/voteset.go, crypto/bls/bls.go, crypto/bls/bls_test.go, state/state_test.go, state/validation_test.go, util/testsuite/testsuite.go
Extract Public Key aggregate function from the VerifyAggregated function. Write some tests. There is still a problem
```
func TestPublicKeyAggregate(t *testing.T) {
pub1, _ := bls.PublicKeyFromString(
public key string 1)
pub2, _ := bls.PublicKeyFromString(
public key string 2)
agg, _ := bls.PublicKeyFromString(
aggregated public key)
assert.True(t, bls.PublicKeyAggregate([]*bls.PublicKey{pub1, pub2}).EqualsTo(agg))
assert.False(t, pub1.EqualsTo(pub2))
}
```
I dont know how to generate the public key and aggregated public key string value to be used as examples in this test
=> refactor: public key aggregate

sync/bundle/bundle_test.go, sync/bundle/message/blocks_response.go, sync/bundle/message/blocks_response_test.go, sync/bundle/message/message.go, sync/handler_blocks_request.go, sync/handler_blocks_request_test.go, sync/handler_blocks_response_test.go, sync/sync.go, sync/sync_test.go
add reason of rejection to block response
- Fixes #526
=> feat: add reason to BlockResponse messages

types/block/block_test.go, types/block/certificate.go, types/block/certificate_test.go
This PR reverts #444.
While it may seem optimal to remove the committer list from the certificate, it's not practical for the following reasons:
1- It's logical for a certificate to include the list of its signers (or committers) alongside the signature.
2- Retrieving the committers of a certificate based on the current state of the blockchain isn't feasible without storing additional information.
=> fix: adding committers to the certificate

.github/workflows/gui.yml, consensus/consensus.go, execution/executor/bond_test.go, sync/peerset/peer_set.go, tests/transaction_test.go
We have encountered a test failure in the system tests, which is caused by a random number for the stake that falls below the minimum threshold. In this pull request (PR), the stake amount has been fixed at 1000000. As a result, we should not experience any random failures in these tests.
Also, we ensure that `currentState` is not `nil` in the consensus.
Also, we ensure that `go1.20` is installed for Windows action.
=> chore: fixing the Windows issue and test failure

network/interface.go, network/mdns_test.go, network/network.go, network/network_test.go, network/notifee.go
I added `EventTypeConnect` and `EventTypeDisconnect` to the Network events to handle the `Connect` and `Disconnect` events. 
- Fixes #622
=> feat: Notifee service events

util/logger/logger.go, util/logger/logger_test.go
If a field in the log is an error, the error message will be printed.
=> fix: error case

sync/bundle/message/hello.go, sync/bundle/message/hello_test.go, sync/handler_blocks_request_test.go, sync/handler_hello.go, sync/handler_hello_test.go, sync/mock.go, sync/peerset/peer.go, sync/peerset/peer_set.go, sync/peerset/peer_set_test.go, sync/sync.go, sync/sync_test.go, util/testsuite/testsuite.go, www/grpc/network.go, www/grpc/network_test.go
aggregating signature for hello message.
- Fixes #547
=> fix: aggregating signature for hello message

.golangci.yml, types/validator/validator.go, wallet/vault/vault_test.go
I enabled `dupword` linter
- Fixes #649
=> chore(linter): enable dupword linter

.github/workflows/gui.yml, .github/workflows/linting.yml, Makefile
from the  `gofumpt` [documents](https://github.com/mvdan/gofumpt/blob/9a108c1953290163d2104befba4a340b5f553001/README.md?plain=1#L10) `gofumpt` is a superset of `gofmt` and using `gofmt` after `gofumpt` doesn't make any changes.
so, we can remove it.
=> chore: remove gofmt and fix golang-ci version

.golangci.yml, consensus/consensus_test.go, consensus/voteset/voteset_test.go, execution/executor/transfer_test.go, network/network_test.go, sandbox/sandbox_test.go, state/lastinfo/last_info_test.go, state/state_test.go, store/store_test.go, sync/firewall/firewall_test.go, sync/sync_test.go, tests/account_test.go, tests/transaction_test.go, tests/validator_test.go, txpool/pool_test.go, util/testsuite/testsuite.go, wallet/vault/vault_test.go, wallet/wallet_test.go, www/grpc/server_test.go, www/http/http_test.go
=> chore: enable thelper linter

network/notifee.go, sync/handler_blocks_request.go, sync/handler_blocks_response_test.go, sync/handler_hello.go, sync/handler_hello_test.go, sync/peerset/peer.go, sync/peerset/peer_set_test.go, sync/peerset/peer_test.go, sync/peerset/status_code.go, sync/sync.go, sync/sync_test.go
I have updated the Hello message from broadcasting to direct messaging. This change will reduce network usage and improve efficiency.
=> refactor: change Hello message from broadcasting to direct messaging

execution/execution.go, state/mock.go, state/state.go, state/state_test.go, txpool/pool.go, types/tx/payload/payload.go, types/tx/payload/unbond.go, types/tx/tx.go, wallet/tx_builder.go, wallet/wallet.go, www/grpc/transaction.go
from the previous PR, we changed `Unbond` to `Unbound`, but the `Unbond` phrase is correct, and changing it to `Unbound` needs a heavy change, so we decided to revert this word.
=> chore: fix unbond typo

committee/committee.go, network/errors.go, network/gossip.go, network/gossip_test.go, network/mdns.go, network/network.go, network/network_test.go, network/stream.go, node/node_test.go, tests/block_test.go, tests/main_test.go
This PR adds a tests to make sure UDP  and IPv6 protocols are supported in the network module. 
Maybe related to #620
=> feat: adding udp protocol for network

types/tx/tx.go, types/tx/tx_test.go
Ensure the `flagStripedPublicKey` is only set for non-subsidy transactions when the public key is nil.
- Fixes #677
=> fix: prevent stripping public key for subsidy transactions

consensus/commit.go, consensus/consensus.go, consensus/height.go, consensus/propose.go, network/bootstrap.go, network/dht.go, network/gossip.go, network/mdns.go, network/network.go, network/stream.go, state/state.go, store/account.go, store/store.go, store/validator.go, sync/firewall/firewall.go, sync/handler_transactions.go, sync/sync.go, txpool/pool.go, util/logger/logger_test.go, www/grpc/network.go, www/grpc/server.go, www/http/server.go, www/nanomsg/event/event.go, www/nanomsg/server.go
Renaming `err` to `error` improves logging in colorful logs.
=> chore: better logging by renaming err to error

sandbox/sandbox.go, sandbox/sandbox_test.go, state/state.go
The genesis can have more than one account. This PR checks if the number of accounts in the store exceeds the number of accounts in the genesis. If it does, it's considered that the blockchain is no longer at the genesis height.
=> fix: restoring at the first block

txpool/pool_test.go
This PR fixes a test that was failing randomly. The cause was that the random height could sometimes be less than `UnbondInterval`.
=> test: fixing a broken test

cmd/cmd.go, config/config.go, config/config_test.go, sync/firewall/firewall.go, sync/firewall/firewall_test.go, sync/handler_blocks_request.go, types/block/block_test.go, types/block/errors.go, types/certificate/errors.go, types/tx/errors.go, types/tx/payload/bond.go, types/tx/payload/bond_test.go, types/tx/payload/errors.go, types/tx/payload/sortition.go, types/tx/payload/sortition_test.go, types/tx/payload/transfer.go, types/tx/payload/transfer_test.go, types/tx/payload/withdraw.go, types/tx/tx.go, types/tx/tx_test.go, types/vote/errors.go, util/logger/logger.go, util/logger/logger_test.go, wallet/errors.go, wallet/wallet.go, wallet/wallet_test.go, www/http/account.go, www/http/blockchain.go, www/http/validator.go
This PR includes some enhancements and fixes for minor issues in the pre-testnet network, including:
- Checking that the number of rewards addresses is the same as the number of validator addresses.
- Verifying that the rewards addresses are account addresses and not validator addresses.
- Improving some log messages.
- Enhancing the HTTP results.
=> fix: fixing some minor issues on pre-testnet

consensus/consensus.go, consensus/consensus_test.go, consensus/height_test.go, consensus/manager.go, consensus/manager_test.go, consensus/mock.go, state/state.go, sync/sync.go
This PR prevents double entry in the new height state within the consensus engine.
=> fix(consensus): prevent double entry in new height

consensus/consensus.go, consensus/cp_decide.go, consensus/cp_mainvote.go, consensus/cp_prevote.go, consensus/cp_test.go, consensus/manager.go
A crash could occur in the consensus if a validator receives all pre-votes for zero before receiving a proposal. In this case, the node crashed because the prepared block hash was nil.
A test is written to reproduce the crash.
=> fix: fixing a crash on consensus

docs/metrics.md
=> docs(metrics): updating with new ports and add some notes

sync/bundle/message/hello.go, sync/bundle/message/hello_test.go, sync/handler_hello.go, sync/handler_hello_test.go
This PR implemented [pip-7](https://pips.pactus.org/PIPs/pip-7)
=> feat: implementing pip-7

consensus/consensus_test.go, consensus/cp_test.go, consensus/log/log_test.go, consensus/manager_test.go, consensus/precommit_test.go, consensus/propose.go, consensus/propose_test.go, execution/execution_test.go, state/execution_test.go, state/facade.go, state/mock.go, state/state.go, state/state_test.go, state/validation_test.go, sync/bundle/message/block_announce_test.go, sync/bundle/message/blocks_response_test.go, sync/bundle/message/proposal_test.go, sync/bundle/message/vote_test.go, sync/handler_blocks_response_test.go, txpool/pool_test.go, types/proposal/proposal.go, types/proposal/proposal_test.go, types/tx/tx_test.go, util/testsuite/testsuite.go, www/http/http_test.go
This PR checks if a block has the maximum number of transactions and removes any extra transactions.
=> fix: fixing issue when a block has max transactions

state/state.go, util/slice.go, util/slice_test.go
This PR trims transactions inside the proposed block to ensure they are not more than `maxTransactionsPerBlock`.
=> fix: trim transactions in proposed block

consensus/consensus.go, consensus/cp.go, consensus/cp_decide.go, consensus/cp_mainvote.go, consensus/cp_prevote.go, consensus/cp_test.go, consensus/precommit.go, consensus/prepare.go, consensus/ticker.go, tests/main_test.go
This PR adds a timer to query votes in change-proposer phase.
=> fix: adding query vote timer for CP phase

config/config.go, config/example_config.toml, network/config.go, network/stream.go, sync/firewall/firewall.go, sync/firewall/firewall_test.go, sync/handler_blocks_request.go, sync/sync.go, tests/main_test.go
This PR replaces QUIC with QUICv1 in the config file. Read more about QUIC protocol [here](https://docs.libp2p.io/concepts/transports/quic/)
=> chore: replacing quic with quic-v1

types/certificate/certificate.go, types/certificate/certificate_test.go
A data race issue could occur when updating the certificate, as we can see here in this [action](https://github.com/pactus-project/pactus/actions/runs/6497684575/job/17647318149?pr=745). This PR deeply clones the certificate to prevent it.
=> fix: data race issue on updating certificate

config/config_test.go, config/example_config.toml, network/config.go, network/dht.go, network/network.go, network/network_test.go, tests/main_test.go
This PR adds bootstrapper mode to the config and operates the DHT as a server.
Fixes: #756
=> feat(network): adding bootstrapper mode to the network config

docs/releasing.md, version/version.go
=> chore: bumping version to 0.16.0

consensus/voteset/binary_voteset.go, consensus/voteset/voteset_test.go
This PR fixes a bug in Binary votes where double votes could increase the voting power.
=> fix(consensus): not increase the voting power on duplicated binary votes

execution/executor/transfer_test.go, util/testsuite/testsuite.go
This PR ensures that the random height is always greater than 1000.
=> test: protect tests from bad random height

consensus/consensus.go, consensus/consensus_test.go, consensus/cp.go, consensus/cp_decide.go, consensus/cp_mainvote.go, consensus/cp_test.go, consensus/log/log.go, consensus/log/messages.go, consensus/voteset/binary_voteset.go, consensus/voteset/block_voteset.go, consensus/voteset/voteset.go, consensus/voteset/voteset_test.go, network/utils.go, types/vote/cp_just.go, types/vote/vote.go, types/vote/vote_test.go, types/vote/vote_type.go
This pull request (PR) implements strong termination for binary agreement. 
Any validator who makes a decision in the MainVote step will broadcast the `decide` message.
Any validator who sees a proper and justified `decide` message can decide on the agreed-upon value and terminate immediately.
This is based on section 5.3.1 of the ABBA spec: "Achieving Stronger Termination"
=> fix(consensus): strong termination for the binary agreement

sync/handler_hello.go, sync/handler_hello_test.go
Peer status should set to known after sending hello-ack message.
=> fix(sync): peer status set to known on sucessfull handshaking

network/gossip.go, network/network.go, network/notifee.go
Set limit for connection in [resource manager](https://github.com/ipfs/kubo/blob/master/docs/libp2p-resource-management.md).
=> fix(network): set connection limit for the resource manager

network/dht.go, network/gossip.go, network/network.go
This PR enables Peer Exchange for bootstrappers.
=> fix(network): enabling peer exchange for bootstrappers

network/network.go, network/notifee.go, network/stream.go
Wait for 10 seconds to get the supported protocols from the newly connected node; if not received, close the connection.
=> fix(network): close connection when unbale to get supported protocols

CHANGELOG.md, docs/patching.md
=> chore: releasing version 0.15.2

cmd/gtk/assets/ui/widget_node.ui, cmd/gtk/widget_node.go, node/node.go
Added a function to return Network object from Node which will help in Displaying the Node ID in the UI. 
- Fixes #761 
/claim #761
=> feat(gui): display network ID

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 0.17.0

network/network.go, network/notifee.go
If the node is a bootstrap node and the protocol negotiation cannot be established, the connection will not be closed.
=> fix: not close connection for bootstrap nodes

config/example_config.toml, network/config.go, network/network.go, network/network_test.go, network/utils.go, tests/main_test.go
This update ensures that private networks can be filtered out, and private IP addresses won't be advertised based on the configuration.
=> feat(network): filter private ips

config/config.go, config/config_test.go, config/example_config.toml, genesis/genesis.go, genesis/genesis_test.go, network/config.go, network/config_test.go, network/dht.go, network/gater.go, network/gater_test.go, network/mock.go, network/network.go, network/network_test.go, network/peermgr.go, network/utils.go, network/utils_test.go, tests/main_test.go
This PR detects public IPs and adds their addresses to the address factory. 
This should help to resolve connection failures.
=> feat(network): adding public address to factory

execution/executor/bond_test.go, execution/executor/unbond.go, execution/executor/unbond_test.go, sandbox/sandbox.go, sync/sync.go, sync/sync_test.go
This PR fixes a mistake in calculating unbonded power. 
It is important to note that the power for an unbonded validator is zero. 
Therefore, when calculating the [powerDelta](https://github.com/pactus-project/pactus/blob/02bff51ade9d7c89a72653f59670e6c3b3c50c77/sandbox/sandbox.go#L264), we should consider the stake, not the power.
=> fix(execution): fixing mistake on calculating unbonded power

sync/config.go, sync/peerset/peer_set.go, sync/peerset/peer_set_test.go, sync/sync.go, sync/sync_test.go
This PR fixes a bug that allows opening an unlimited number of sessions in bootstrap nodes.
=> fix(sync): prevent opening sessions indefinitely

cmd/cmd.go, config/config.go, config/example_config.toml, network/config.go, network/config_test.go, network/dht.go, network/gossip.go, network/network.go, network/network_test.go, tests/main_test.go
This PR adds new private configs for default bootstrap and relay peers.
=> feat(network): default configs for bootstrap and relay peers

config/config.go, config/config_test.go, network/gossip.go, network/utils.go, network/utils_test.go, sync/bundle/bundle.go, sync/bundle/bundle_test.go, sync/firewall/firewall_test.go, sync/handler_block_announce.go, sync/handler_blocks_request.go, sync/handler_blocks_response.go, sync/handler_blocks_response_test.go, sync/handler_hello.go, sync/handler_hello_ack.go, sync/handler_hello_test.go, sync/handler_proposal.go, sync/handler_proposal_test.go, sync/handler_query_proposal.go, sync/handler_query_votes.go, sync/handler_transactions.go, sync/handler_transactions_test.go, sync/handler_vote.go, sync/handler_vote_test.go, sync/sync.go, sync/sync_test.go
This PR upgrades the Testnet by changing the pubsub options. 
Nodes prior to this version will be unable to connect to the network, and the upgrade is mandatory.
BREAKING CHANGE
=> fix!: upgrading Testnet

sync/handler_blocks_response_test.go, sync/peerset/peer_set_test.go, sync/peerset/session/session.go, sync/sync.go, sync/sync_test.go
This PR updates the logic to avoid sending the block request message if the requested blocks are already present in the cache.
=> fix(sync): ignore block request if blocks are already inside the cache

util/logger/logger.go
current log time format:
```sh
2023-11-17T10:40:25Z WRN connection failed _network={2} addr=["/ip4/51.158.118.181/tcp/21777"] err="failed to dial: context canceled"
2023-11-17T10:40:25Z WRN connection failed _network={2} addr=["/ip4/172.104.46.145/tcp/21777"] err="failed to dial: context canceled"
2023-11-17T10:40:25Z INF disconnected from peer _network={0} pid=12D3KooWBGNEH8NqdK1UddSnPV1yRHGLYpaQUcnujC24s7YNWPiq
2023-11-17T10:40:25Z INF disconnected from peer _network={0} pid=12D3KooWCwQZt8UriVXobQHPXPR8m83eceXVoeT6brPNiBHomebc
```
- Fixes #808
=> chore(logeer): change colorful logger time-format

config/example_config.toml, util/logger/config.go, util/logger/logger.go
we have 3 new options for logger config now.
the reason for a lot of compressed backup files was enabling compress by default, not setting max-age and rotate interval for them.
but now, all of them in configurable.
- Fixes #755
=> feat(logger): adding rotate log file after days, compress and maxgae for logger config

consensus/manager.go, network/gater_test.go, network/interface.go, network/network.go, network/notifee.go, network/peermgr.go, network/peermgr_test.go, sync/sync.go, sync/sync_test.go
Subscribing to the EventBus of LibP2P helped us figure out when we have a healthy direct connection with a peer. This enables us to send the `connect` event more effectively and initiate handshaking with a peer.
=> fix(network): subscribing to the Libp2p event bus

network/gossip.go, network/network_test.go, network/notifee.go, sync/handler_blocks_request.go, sync/handler_blocks_response.go, sync/peerset/peer_set.go, sync/sync.go, sync/sync_test.go
This PR checks if a new block has been received before; if it has, it won't be published again. 
The purpose of this change is to reduce network bandwidth usage by preventing the unnecessary publication of new blocks by all validators.
=> fix(sync): ignore publishing a block if it is received before

crypto/hash/hash.go, crypto/hash/hash_test.go, state/validation_test.go, sync/handler_block_announce_test.go, types/block/block_test.go, types/block/header.go
This PR removes `BasicCheck` method from the hash.
=> fix: removing BasicCheck for hash

cmd/cmd.go
This PR set working directory to `/root/pactus` instead of `/pactus` for root users (or inside docker)
It is going to fix #842
=> fix(cmd): changing home directory for root users

cmd/cmd.go, config/config.go, config/config_test.go
If a user deletes the configuration file, the node will automatically generate a new configuration file with default values when it is run again.
Fixing #478
=> fix(config): restore default config when it is deleted

cmd/cmd.go, wallet/addresspath/path.go, wallet/vault/utils.go, wallet/vault/vault.go, wallet/vault/vault_test.go, wallet/wallet_test.go
This PR fixes a mistake in retrieving the reward address. It also adds tests for the imported private key.
=> fix: corrected mistake when retrieving the reward address

util/logger/logger.go
This PR creates one writer when initializing the global logger to prevent the file from being locked by sub-loggers.
- Fixes #858
=> fix: fixing logger issue on rotating log file

execution/executor/bond.go, execution/executor/bond_test.go, sandbox/mock.go
This PR checks if the validator has just been created in the sandbox by verifying the validator height. 
It prevents transaction rejection if the public key is set correctly.
- Fixes #869
=> fix(execution): fixing issue #869

docs/patching.md, version/version.go
=> chore: bumping version to 0.18.3

consensus/consensus.go, consensus/consensus_test.go, sync/bundle/message/query_proposal.go, sync/bundle/message/query_proposal_test.go, sync/bundle/message/query_votes.go, sync/bundle/message/query_votes_test.go, sync/firewall/firewall_test.go, sync/handler_query_proposal_test.go, sync/handler_query_votes_test.go, sync/peerset/service/services_test.go, sync/sync_test.go
Add querier to `QueryVote` and `QueryProposal` messages by including the address of the querier. This serves two purposes:
1. Provides which node is querying the vote or proposal.
2. Prevents message ID collisions when multiple nodes query the same vote or proposal, since the querier address are not the same.
=> fix: adding querier to query messages

network/config.go, network/config_test.go, network/dht.go, network/gossip.go, network/network.go, network/notifee.go, node/node.go
This PR turns off the mesh for gossiper nodes, allows it to gossip messages to more peers.
=> fix(network): turn off mesh for gossiper node

network/gossip.go, sync/bundle/bundle.go, sync/bundle/bundle_test.go, sync/peerset/peer_set.go, sync/peerset/peer_set_test.go, sync/sync.go, sync/sync_test.go
This PR adds a sequence number to the bundle.
=> fix(sync): adding sequence number to the bundle

network/gossip.go
This PR refines the GossipSubParams due to a significant increase in network bandwidth in previous changes #880.
=> fix(network): refining GossipSubParams for Gossiper node

network/network.go, network/network_test.go, network/notifee.go, network/peermgr.go, network/relay_service.go, network/utils.go, sync/handler_hello.go
Relay nodes are operating separately. In this PR, we add a relay service to connect to relay nodes if the node's reachability is private. This service checks every minute to ensure there is a connection with the relay nodes.
=> feat(network): adding relay service to dial relay nodes

execution/executor/bond.go, execution/executor/bond_test.go, sandbox/mock.go
This PR reverts PR #870  and fixes issue #900.
- Fixes #900 (Related to #869 )
=> fix(executor): not rejecting bond transaction for bootstrap validator

config/config.go, store/account.go, store/account_test.go, store/block.go, store/config.go, store/config_test.go, store/errors.go, store/store.go, store/store_test.go
This PR uses a cache to check if a public key exists or not. If not, it looks up the DB. 
It also defines a new error for invalid config data.
=> fix(store): use cache to check if public key exists

cmd/gtk/assets/ui/dialog_transaction_unbond.ui, cmd/gtk/assets/ui/dialog_transaction_withdraw.ui, cmd/gtk/dialog_transaction_bond.go, cmd/gtk/dialog_transaction_transfer.go, cmd/gtk/dialog_transaction_unbond.go, cmd/gtk/dialog_transaction_withdraw.go, cmd/gtk/main_window.go, consensus/propose.go
This PR:
- Fixes a typo in the Unbond dialog.
- Adds the account addresses to the receiver entry in the withdraw dialog.
- Uses `AllValidatorAddresses` from the wallet to retrieve validator addresses.
=> fix(GUI): updating unbond and withdraw dialogs

config/example_config.toml, network/config.go, network/network.go, network/network_test.go
This PR adds a new config to the network module to enable or disable the UDP transport protocol.
=> feat(network): adding 'enable_udp' config

config/config.go, config/config_test.go, network/config.go, network/network.go
The relay address field in the config file has a default value. Users do not need to define the listening addresses.
=> feat(network): making listen address private in config

network/network.go
This PR prevents a deadlock on stopping the node that happens on Linux ARM 64.
=> fix(network): fixing network deadlock on linux arm64

node/node.go
Due to the calculation of the Availability score that taking time, a message from the open connection might be received with a delay, causing the rejection of the hello message. This PR starts the node before the network to prevent this situation.
=> fix: fixing time lag on starting node

config/config.go, config/example_config.toml, consensus/config.go, consensus/config_test.go, consensus/errors.go, consensus/propose.go
This changes will add the pip19 score to consensus config, and changes the consensus module to a zero-config module.
=> feat(consensus): turning consensus to a zero-config module

cmd/daemon/init.go
In this PR I removed the validator number, password, and entropy as prompt and hard-coded values. now we get them as flags from the user, this helps other interfaces and clients like GUI use this `init` command with ease.
=> chore(daemon): removing password, entropy and validator number as prompt, and adding flags instead

cmd/gtk/main.go
CMD PR #871
check gui already running by lock file
- Fixes #805
=> feat: pactus gui lock support

CONTRIBUTING.md, cmd/daemon/init.go, cmd/daemon/start.go, cmd/daemon/version.go, cmd/wallet/address.go, cmd/wallet/create.go, cmd/wallet/history.go, cmd/wallet/recover.go, cmd/wallet/tx.go
This PR will update the password option in the daemon CLI init subcommand. also adds new rules for CLI and other modules helper messages and descriptions.
=> fix(daemon): keeping previous behavior for password flag, linting CLI messages

sync/bundle/message/hello.go, sync/bundle/message/hello_test.go, sync/handler_hello_test.go, sync/sync.go, www/grpc/network.go, www/grpc/network_test.go
removed `ReachabilityStatus`.
- removed `ReachabilityStatus` from sync, network and test cases.
=> fix(sync): remove ReachabilityStatus from agent info

network/network_test.go
This PR attempts to prevent some random test failures in the network module by increasing the receive timeout. An example of this random failure can be found here: [https://github.com/pactus-project/pactus/actions/runs/7773841154/job/21197991877?pr=1044](https://github.com/pactus-project/pactus/actions/runs/7773841154/job/21197991877?pr=1044).
=> test: increase receive timeout in tests

network/utils.go
This PR redefines resource limits, specially it set `ConnsOutbound` same as `Conns`. We have many "system: cannot reserve outbound connection: resource limit exceeded" warning messages.
=> fix(network): redefine resource limits

network/peermgr.go
This PR attempts to free up some connections in bootstrap nodes when the node reaches its limit.
This issue is discussed here: https://github.com/libp2p/go-libp2p/issues/2616
=> fix(network): prune connections on bootstrap nodes

network/utils.go
This PR redefines resource limits, specially it set `ConnsOutbound` and `ConnsInbound` same as `Conns`. We have many "system: cannot reserve outbound connection: resource limit exceeded" warning messages.
=>  fix(network): redefine resource limits

network/config.go, network/config_test.go, network/gater.go, network/gater_test.go, network/network.go, network/peermgr.go, network/peermgr_test.go, network/utils.go
This PR establishes limits for inbound and outbound connections. 
By default, each peer can have a up to maximum number of connections for inbound connections, but outbound connections are limited to a quarter of that.
=> fix(network): set dial and accept limit in connection gater

cmd/gtk/assets/ui/widget_node.ui, cmd/gtk/widget_node.go, network/interface.go, network/mock.go, network/network.go, network/peermgr_test.go
This PR adds new fields to the main window on the GUI: Connections and Moniker. 
"Connections" shows the number of connected peers, and "Moniker" displays the moniker of the node.
=> feat(gui): add connections and moniker fields to main windows

docs/patching.md, version/version.go
=> chore: bumping version to 1.0.2

network/peermgr.go, network/peermgr_test.go
This PR loops over all connected peers in PeerMgr and removes those who are not connected. 
This helps to remove disconnected peers if, for any reason, the disconnected event is missed.
- Fixes #1108
=> fix(network): remove disconnected peers from peerMgr

committee/committee.go, network/peermgr.go, store/store.go, sync/peerset/peer_set.go, sync/peerset/peer_set_test.go, sync/sync.go
A concurrent map iteration and map write crash occurred when `IteratePeers` was called by gRPC and the Peers map was updated simultaneously. This patch fixes this crash.
=> fix(sync): fix concurrent map read-write crash

cmd/wallet/history.go
The history add sub-commands needs 1 argument which is the transaction ID. we have to make sure user provides it. otherwise we will panic, which is not a good practice.
- Fixes #1140
=> fix(wallet): checking args in history add

Makefile, www/grpc/gateway.go
This PR fixes the 404 error on calling all gRPC-Gateway APIS.
=> fix(grpc): fix error 404 on grpc gateway

.golangci.yml
Removing unused `funlen` from `.golangci.yml`
=> chore: remove funlen from .golangci.yml

cmd/cmd.go, config/example_config.toml
This PR saves the Mainet configs with the in-line comments upon creating the node.
=> fix: save Mainnet config with inline comments

config/config.go, config/errors.go, store/config.go, store/config_test.go, store/errors.go, txpool/config.go, txpool/errors.go, util/errors/errors.go
This PR defines `ConfigError` type for internal modules.
It partially fixes issue #315
=> fix: add error type for invalid configs

www/grpc/gateway.go
This PR fixs `pactus.swagger.json` no found issue on gRPC gateway.
=> fix(gRPC): pactus swagger not found

config/config.go, config/config_test.go, config/example_config.toml
Fix the issue where the logger level doesn't load properly for the Mainnet config.
=> fix(config): load logger levels in Mainnet config

network/peermgr.go
Some connected peers have no supporting protocols. Closing these connections allows the node to find better connections.
=> fix: close connections with peers that have no supported protocol

cmd/gtk/assets/ui/dialog_transaction_bond.ui, cmd/gtk/assets/ui/dialog_transaction_transfer.ui, cmd/gtk/assets/ui/dialog_transaction_unbond.ui, cmd/gtk/assets/ui/dialog_transaction_withdraw.ui, cmd/gtk/dialog_transaction_bond.go, cmd/gtk/dialog_transaction_transfer.go, cmd/gtk/dialog_transaction_unbond.go, cmd/gtk/dialog_transaction_withdraw.go
With these changes, users can use the memo option in the GUI wallet. so, the applications that use memos for any reason can be able for GUI wallet users too.
> @b00f, I've just made this PR and closed the previous one.
=> feat(GUI): memo field for transactions on GUI wallet

cmd/gtk/utils.go
The GUI Users can see the transaction hash while it sent to the network and they can track it on Explorer or their node.
=> feat(GUI): showing transaction hash after broadcasting transaction

www/grpc/buf/grpc-gateway.config.yaml
Add `GetNewAddress` and `GetTotalBalance` endpoint to gateway
=> feat(grpc): Add GetNewAddress/GetTotalBalance endpoint to gateway

execution/errors.go, execution/execution.go, execution/execution_test.go, state/mock.go, state/state.go, state/state_test.go, types/tx/tx.go, types/tx/tx_test.go, types/vote/errors.go, util/errors/errors.go, www/grpc/transaction.go, www/grpc/transaction_test.go
This PR includes changes related to fee calculation:
1. Fixed an issue with calculating unbonding fees, which should be set to zero.
2. No longer returns an error on zero amounts.
3. Moved the fee calculation logic to the execution package.
=> refactor: move fee calculation logic to execution package 

cmd/wallet/address.go
This PR ignores errors in balance and stake queries on an address.
=> fix(cmd): ignore error on balance query

execution/executor/bond.go, execution/executor/bond_test.go, execution/executor/sortition.go, execution/executor/sortition_test.go, execution/executor/transfer_test.go, execution/executor/unbond_test.go, execution/executor/withdraw_test.go, sandbox/mock.go
This pull request prevents zero stakes and helps validators with amounts less than one to reach full stake.
=> fix: prevent zero stake for bond transactions

config/banned.json
Remove `pc1pfdtn220dvh0wf38q4j2nqjq264t0d7e8ep9ukx` from the banned list.
We have recently faced several attacks on the Pactus blockchain that interrupted block creation. 
None of the attacks could damage users' assets, but they potentially hurt other validators in two ways:
1. By sending Zero Bond transactions (Issue #1223), the attacker(s) prevent other validators from receiving block rewards accordingly.
2. By sending spamming transactions (Issue #1232), it interrupts block creation and, in some cases, reduces the availability score of some validators.
After the investigation, we found these accounts as sources of attacks:
- pc1zusayxszmntpjf359fm4tpvj9kj2g8uqjt83d5v
- pc1z6d9kvyqld7ah0ql8c5duvrjz7ery74k07yysvw
- pc1zm4d6lu8j83qp6skd9g0566ewa8t2qvjwk65949
A total of 26,301 transactions …
=> chore: remove an address from banned list

.github/workflows/releaser.yml
This PR replace the self hosted macos runner to github runner
=> chore: use github macos runner instead of self hosted

node/node.go, wallet/manager.go, www/grpc/server.go, www/grpc/server_test.go, www/grpc/wallet.go, www/http/http_test.go
=> feat: add wallet service

config/bootstrap.json, config/config.go, execution/executor/bond_test.go, network/config.go, network/config_test.go, network/gater.go, network/gater_test.go, network/network.go, network/notifee.go, network/peermgr.go, network/peermgr_test.go, network/utils.go, sync/handler_blocks_request.go, sync/handler_hello_ack.go, sync/peerset/peer.go, sync/peerset/peer_set.go, sync/peerset/peer_test.go, sync/peerset/status_code.go, sync/sync.go, util/testsuite/testsuite.go
This PR refactors the peer manager. 
It keeps a list of all connected peers and tries to reconnect to them if the number of connected peers falls below the minimum connection threshold.
=> refactor(network): refactor peer manager and redefine the min cons

network/network.go, network/utils.go, www/grpc/network.go
This PR fixes a mistake on resource manager limit. The high watermark limit should be a bit less than the rcmgr connections limit.
Otherwise "High Watermark" trimming never happens because it's higher than the rcmgr limit. 
Read more here:
https://github.com/libp2p/go-libp2p/issues/2628#issuecomment-1809829270
=> fix(network): set infinite limit for resource manager 

cmd/daemon/version.go, cmd/gtk/dialog_about.go, node/node.go, version/version.go
This PR add alias to version information
#1266
=> feat(version): add alias to node version

execution/errors.go, execution/execution.go, state/state.go, txpool/pool.go, txpool/txpool_test.go
This PR  changes `CalculateFee` to be backward compatible with the previous versions.
=> fix: change CalculateFee to be backward compatible

docs/patching.md, version/version.go
=> chore: bumping version to 1.1.6

consensus/config.go, consensus/consensus.go, consensus/cp.go
This PR applies the following patches to the consensus:
1. Once a validator sees a proper and justified "Decided" vote, it moves the consensus to the vote's round, even if it is a prior round.
2. Considering 1/3 of faulty nodes in a faulty network, the minimum availability score is set to 0.666.
=> fix(consensus): move to new round on decided vote

sync/config.go
This PR updates the latest supported version to 1.1.6. As a result, connections with nodes running lower versions will be rejected.
=> fix(network): set latest support version to 1.1.6

docs/patching.md, version/version.go
=> chore: bumping version to 1.1.7

consensus/consensus.go, consensus/interface.go, consensus/manager.go, consensus/mock.go, sync/handler_proposal_test.go, sync/handler_query_proposal_test.go
The proposer responds to the query-proposal message. This helps to reduce the number of consensus messages.
=> fix(consensus): only proposer responds to the query proposal

docs/patching.md, version/version.go
=> chore: bumping version to 1.1.8

consensus/consensus.go, consensus/consensus_test.go, sync/bundle/message/query_proposal.go, sync/bundle/message/query_proposal_test.go, sync/handler_query_proposal.go, sync/handler_query_proposal_test.go, sync/handler_query_votes.go, sync/sync_test.go
This PR adds a round to the query proposal message. By doing so, messages with expired rounds will be ignored.
=> fix(consensus): add round to query proposal message

docs/patching.md, version/version.go
=> chore: bumping version to 1.1.9

go.mod, go.sum, www/grpc/basicauth/basicauth_test.go, www/grpc/middleware.go, www/grpc/middleware_test.go, www/grpc/server.go, www/http/server.go, www/jsonrpc/server.go
- add GRPC recovery middleware to prevent crash server on grpc
- add GRPC retry middleware to reconnection client
=> fix(grpc): improve grpc server and client

consensus/config.go, fastconsensus/config.go, www/grpc/gateway.go
This PR implements the [PIP-26](https://pips.pactus.org/PIPs/pip-26).
It updates the Minimum Availability Score to 0.666667.
=> fix(consensus): implement PIP-26

consensus/propose.go, fastconsensus/propose.go, state/state.go
Instead of decoding the full block, use the block header to obtain the prev certificate.
- Fixes #1337
=> fix(state): improve node startup by optimizing availability score calculation

network/gossip.go, network/network_test.go
This PR adds more logs for the NetworkTest to trace the test failure.
=> test: add more logs for network-test

util/ntp/ntp.go
Change log level warn to debug for pools query.
- Fixes #1361
=> chore(ntp): change log level to debug

consensus/consensus.go, fastconsensus/consensus.go, network/gossip.go, network/gossip_test.go, network/interface.go, network/mdns_test.go, network/mock.go, network/network.go, network/network_test.go, network/stream.go, sync/sync.go, sync/sync_test.go
We had a known issue that happened occasionally. Sometimes 
the nodes would lag for a minute and then start syncing. This PR fixes this issue. 
The main reason was that once `SendTo` blocked (for any reason), the receiving loop also got stuck. 
Here, we send messages asynchronously to ensure the receiving loop doesn't get blocked.
=> fix(network): use goroutines for sending streams

cmd/gtk/main.go
GUI support `ctrl+c` for interrupt process.
- Fixes #1321
=> fix(gui): support ctrl+c for interrupt gui

network/network_test.go
This PR adds temporary path to `peerstore` inside tests.
=> test(network): add path to peerstore in Network tests

cmd/shell/main.go
Before pactus shell don't pass authentication basic auth for gRPC, currently supported and pass switchs:
- `--auth-username`
- `--auth-password`
- Fixes #1376
=> fix(pactus-shell): pactus shell support basic auth

cmd/cmd.go, cmd/gtk/main.go, cmd/wallet/main.go, wallet/client.go, wallet/manager.go, wallet/options.go, wallet/wallet.go, wallet/wallet_test.go
This PR introduces a client timeout for connections when dialing to the server. The primary goal is to prevent delays during query retrieval by setting a maximum duration for establishing a connection. This ensures that if a server is unresponsive or slow, the client will not hang indefinitely, thereby improving the overall responsiveness and reliability of the application.
=> feat(wallet): add timeout client connection

store/store.go
This PR implements the prune block function defined on PIP-27.
- Fixes #1391
=> feat(store): prune block function

cmd/cmd.go, cmd/daemon/init.go, cmd/daemon/main.go, cmd/daemon/prune.go, cmd/daemon/start.go, config/example_config.toml, store/config.go, store/interface.go, store/mock.go, store/store.go
The prune command optimizes blockchain storage by removing outdated blocks and transactions, freeing up disk space and enhancing client performance.
- Fixes #1392
=> feat(core): pruning client by prune command

genesis/genesis.go, state/state.go, state/state_test.go, store/block.go, store/block_test.go, store/config.go, store/interface.go, store/mock.go, store/store.go, tests/main_test.go, types/block/block.go, types/block/block_test.go
This PR adds prune on a new block for pruned nodes.
- Fixes #1393
=> feat(state): prune block on commit

www/grpc/utils.go, www/grpc/utils_test.go
This PR enhances error handling by returning `InvalidArgument` error when the Public Key or Signature is invalid. 
This improvement allows users to distinguish between an invalid argument and a signature that does not match the signed message.
=> fix(grpc): return error on invalid arguments for VerifyMessage

state/state.go
This PR sets the maximum number of transactions in a block to 1000.
=> chore(state): revet maximum transaction in block to 1000

store/mock.go, store/store.go, store/store_test.go, www/grpc/blockchain.go, www/grpc/blockchain_test.go
Updated the `PruningHeight` function to correctly return zero if the store is not in prune mode.
=> fix(store): pruning height returns zero when store is not in prune mode

cmd/daemon/import.go, cmd/gtk/startup_assistant.go, cmd/importer.go, util/io.go, util/io_test.go
This PR prevents a sudden panic if downloading data encounters an error. 
It also creates the parent directory to prevent an error when moving data.
=> fix(cmd): prevent sudden crash on download error

consensus/consensus.go, consensus/consensus_test.go, consensus/cp.go, consensus/cp_prevote.go, consensus/interface.go, consensus/manager.go, consensus/mock.go, consensus/precommit.go, consensus/prepare.go, consensus/prepare_test.go, consensus/ticker.go, sync/bundle/message/message.go, sync/bundle/message/query_votes.go, sync/bundle/message/query_votes_test.go, sync/firewall/firewall_test.go, sync/handler_proposal_test.go, sync/handler_query_proposal.go, sync/handler_query_proposal_test.go, sync/handler_query_votes.go, sync/handler_query_votes_test.go, sync/handler_vote_test.go, sync/sync.go
When the validators decide not to change the proposer and the proposal gets locked, the `QueryProposal` message can be responded to by all validators. 
This ensures that if the proposer fails, the proposal can still be broadcasted by other validators.
=> fix(consensus): handle query for decided proposal

consensus/consensus_test.go, consensus/precommit_test.go, execution/execution_test.go, execution/executor/bond_test.go, execution/executor/transfer_test.go, execution/executor/unbond_test.go, execution/executor/withdraw_test.go, state/execution_test.go, state/state.go, state/state_test.go, store/store_test.go, tests/transaction_test.go, txpool/txpool_test.go, types/tx/factory.go, types/tx/tx.go, types/tx/tx_test.go, util/testsuite/testsuite.go, wallet/tx_builder.go, www/grpc/transaction.go, www/grpc/wallet_test.go
Making `memo` field optional in the `newTx` and its callers functions, by using options pattern.
- Fixes #1440
=> refactor(types): using options pattern for memo parameter on new tx functions

consensus/consensus.go, consensus/height.go, execution/executor/bond_test.go, genesis/genesis_test.go, node/node.go, node/node_test.go, state/execution_test.go, state/lastinfo/last_info_test.go, state/state.go, tests/main_test.go, util/testsuite/testsuite.go, util/time.go, util/time_test.go
We use `time.Now` instead of `util.Now` in this PR.
=> fix(util): remove util.Now helper function

config/config.go, www/grpc/config.go
Check the credential before starting the node
- Fixes #1389
=> fix(grpc): add basic check for grpc configuration to check basic auth

Makefile, www/grpc/buf/json-rpc-md.tmpl, www/grpc/gen/docs/grpc.md, www/grpc/gen/docs/json-rpc.md, www/grpc/gen/go/blockchain.pb.go, www/grpc/gen/java/pactus/blockchain/BlockchainOuterClass.java, www/grpc/gen/rust/pactus.rs, www/grpc/swagger-ui/pactus.swagger.json
Add example json-rpc in doc template
=> fix(grpc): add example json-rpc in generated doc

cmd/daemon/prune.go
This is not a logic change, this change only helps the user to understand what exactly happens when they try to prune a database that is not passed `retention_days`, is already pruned, or is at genesis.
I added this since I was working on the previous PR when I was trying to Prune my recently started node and it was telling me it's pruned successfully!!!
But after a check I saw it's still a full node. Then I remembered It needs to pass the retention_days first. so it's a helpful message.
This can improve both UX and DX.
=> feat(daemon): warn at pruning a prune node attempt

scripts/snapshot.py, www/grpc/buf/buf.gen.yaml, www/grpc/gen/python/blockchain_pb2.pyi, www/grpc/gen/python/network_pb2.pyi, www/grpc/gen/python/transaction_pb2.pyi, www/grpc/gen/python/utils_pb2.pyi, www/grpc/gen/python/wallet_pb2.pyi
Python GRPC auto-generated files need some `.pyi` files which contain detailed objects of requests.
Example:
https://github.com/Tinkoff/invest-python/tree/main/tinkoff/invest/grpc
Also, it's essential for the pactus-python-sdk.
=> fix(grpc): adding pyi files for python generated files

crypto/bls/bls_test.go
It adds a new test for hash-to-curve function from the RFC9380.
=> test(crypto): add test for hash-to-curve

crypto/address.go, crypto/address_test.go, crypto/bls/bls_test.go, crypto/bls/private_key.go, crypto/bls/private_key_test.go, crypto/bls/public_key.go, crypto/bls/public_key_test.go, crypto/bls/signature.go, crypto/bls/signature_test.go, crypto/ed25519/ed25519_test.go, crypto/ed25519/private_key.go, crypto/ed25519/private_key_test.go, crypto/ed25519/public_key.go, crypto/ed25519/public_key_test.go, crypto/ed25519/signature.go, crypto/ed25519/signature_test.go, crypto/hash/hash_test.go, network/utils_test.go, util/testsuite/testsuite.go, wallet/manager.go
This PR update tests for Ed25519 curve.
=> test(crypto): update Ed25519 tests

cmd/wallet/address.go, crypto/address.go, crypto/address_test.go, types/tx/errors.go, types/tx/tx.go, types/tx/tx_test.go, util/testsuite/testsuite.go, wallet/vault/vault.go, wallet/vault/vault_test.go, wallet/wallet.go, wallet/wallet_test.go
In this PR the Ed25519 cryptography is supported for creating new addresses
- Fixes #1482
=> feat(wallet): supporting Ed25519 curve in wallet

cmd/gtk/assets/ui/dialog_wallet_create_address.ui, cmd/gtk/dialog_wallet_create_address.go
This PR support generation Ed25519 account type on GTK.
- Fixes #1486
=> feat(gtk): support create Ed25519 in gtk

genesis/genesis.go, genesis/genesis_test.go, state/execution.go
This PR enables Ed25519 curve for the Testnet (it is still disabled for the Mainnet).
This is a hard fork, meaning all nodes will need to upgrade in the future.
Please review it carefully.
=> feat(state): enable Ed25519 for the Testnet

cmd/wallet/history.go, cmd/wallet/info.go, cmd/wallet/main.go, wallet/history_test.go, wallet/manager.go, wallet/wallet.go
Adding `info` commands for `pactus-wallet`
- https://github.com/pactus-project/pactus/issues/1494
=> feat(cmd): pactus-wallet add info commands

consensus/consensus_test.go
This PR fixes a random test failure in `TestByzantine`, as explained in #1452.
This situation is highly unlikely to occur on the mainnet, and even if it does, restarting any node will resolve the consensus halt.
To avoid adding unnecessary complexity to the codebase, we may choose not to address this issue further.
- Fixes #1452
=> test(consensus): fix occasional failure in Byzantine test

state/errors.go, state/execution.go, state/execution_test.go, state/state.go, state/validation.go, state/validation_test.go, types/proposal/errors.go, types/proposal/proposal.go, types/proposal/proposal_test.go, util/errors/errors.go, util/errors/errors_test.go
Removes ErrInvalidBlock from tests.
- Partially Fixes #315
=> refactor(state): define errors for state package

consensus/cp.go, consensus/cp_test.go, consensus/errors.go, consensus/voteset/binary_voteset.go, consensus/voteset/block_voteset.go, consensus/voteset/errors.go, consensus/voteset/voteset.go, consensus/voteset/voteset_test.go, types/vote/cp_vote.go, types/vote/vote.go, types/vote/vote_test.go, util/errors/errors.go
This PR defines errors for the vote package.
- Partially Fixes #315
=> refactor(types): define errors for vote package

sync/bundle/bundle.go, sync/bundle/message/blocks_request.go, sync/bundle/message/blocks_request_test.go, sync/bundle/message/errors.go, sync/bundle/message/hello.go, sync/bundle/message/hello_test.go, sync/bundle/message/message.go, sync/bundle/message/message_test.go, sync/bundle/message/query_proposal.go, sync/bundle/message/query_proposal_test.go, sync/bundle/message/query_votes.go, sync/bundle/message/query_votes_test.go, sync/bundle/message/transactions.go, sync/bundle/message/transactions_test.go, sync/firewall/errors.go, sync/firewall/firewall.go, sync/firewall/firewall_test.go, util/errors/errors.go, www/grpc/wallet_test.go
This PR defines error types for the sync package.
- Partially Fixes #315
=> refactor(sync): define errors for sync package

cmd/daemon/start.go, www/http/server.go
Remove duplicate http server on pprof feature and as default pprof registered to http transport.
=> fix(cmd): add pprof as default in http server

crypto/bls/bls.go, crypto/bls/bls_bench_test.go, crypto/bls/bls_test.go, crypto/bls/private_key.go, crypto/bls/private_key_test.go, crypto/bls/public_key.go, crypto/bls/public_key_test.go, crypto/bls/signature.go, crypto/bls/signature_test.go, crypto/errors.go, go.mod, go.sum, util/slice.go, util/slice_test.go
This PR replace BLS12-381 [kilic](https://github.com/kilic/bls12-381) with [gnark](https://github.com/consensys/gnark-crypto). The benchmark:
```
BenchmarkVerify-8 (OLD)               1008       1227301 ns/op       67792 B/op         159 allocs/op
BenchmarkVerify-8 (NEW)               1279        992421 ns/op        6373 B/op          59 allocs/op
```
This PR will close #955
=> refactor(crypto): replace bls12-381 kilic with gnark

cmd/cmd.go, cmd/daemon/start.go, cmd/gtk/main.go, www/http/config.go, www/http/server.go
Add flag debug to enable pprof
=> fix(cmd): add flag debug to enable pprof

cmd/cmd.go, cmd/daemon/start.go, cmd/gtk/main.go, config/config.go, config/example_config.toml, www/http/config.go, www/http/server.go
Add pprof on http server with configuration
- add enable_pprof in config
- fully disable pprof on mux server
- add example config for pprof
- remove debug flag in cmd
=> fix(http): pprof in http server

sync/config.go, sync/handler_blocks_request.go
This PR sets the last supported version to 1.5.0, which includes the hard fork for Ed25519 curve support. 
Peers using a lower version will have their hello messages rejected.
=> fix(sync): set last support version to 1.5.0

www/http/server.go
Show `/debug/pprof` in web link list in http.
=> fix(http): add pprof link in http web interface

go.mod, network/config.go, network/gossip.go, network/network.go, network/network_test.go, network/notifee.go, network/stream.go, network/stream_test.go, network/utils.go, sync/sync_test.go, txpool/txpool_test.go
This PR closes the stream once the timeout expires. 
This ensures all streams are closed, even if the receiver didn't close them.
=> fix(network): close stream on timeout

go.mod
Upgrade go to v1.23.2 to fix issue go-libp2p https://github.com/libp2p/go-libp2p/issues/2968
=> chore(deps): upgrade go to 1.23.2 to fix libp2p issue

Dockerfile
Updated go version docker image to build go v1.23.2
=> fix(deps): go version docker image to build go v1.23.2

.github/workflows/coverage.yml, .github/workflows/deadlock.yml, .github/workflows/gui.yml, .github/workflows/linting.yml, .github/workflows/releaser.yml, .github/workflows/testing.yml
This PR updates the go version inside the GitHub actions to `1.23.2` and also signs the `SHA256SUMS` file using [cosign](https://github.com/sigstore/cosign).
- Fixes #1216 (We don't use GPG)
=> ci(release): sign SHA256SUMS using cosign

state/execution.go
This PR sets the hard-fork height to `2,320,000` to introduce support for Ed25519.  
Currently, the Ed25519 curve is supported on the Testnet.
=> fix(state): set hard-fork height for the mainnet

cmd/gtk/assets/ui/main_window.ui
Fix width of main window gtk for show correct availability score.
**Before:**
**After:**
=> fix(gtk): increase window width to show availability score

www/grpc/buf/grpc-md.tmpl, www/grpc/buf/json-rpc-md.tmpl, www/grpc/gen/docs/grpc.md, www/grpc/gen/docs/json-rpc.md
Remove trailing spaces in generated and template of gRPC documentation.
=> chore(grpc): remove trailing spaces from gRPC doc template

crypto/bls/public_key.go, crypto/bls/public_key_test.go, crypto/bls/signature.go, crypto/bls/signature_test.go, crypto/ed25519/public_key.go, crypto/ed25519/public_key_test.go, crypto/ed25519/signature.go, crypto/ed25519/signature_test.go, crypto/public_key.go, crypto/signature.go, types/tx/tx.go, types/tx/tx_test.go
This PR defines the `SerializeSize` method for both `PublicKey` and `Signature`. It simplifies the transaction encoding.
=> refactor(crypto): define SerializeSize for PublicKey and Signature

cmd/gtk/assets/ui/widget_node.ui
- Rename "Is Prune" to "Pruned" and move it to top after "Reachability"
- Rename "Number of blocks left" to "Remaining Blocks"
- Fixes #1490
=> fix(gtk): change some text in GUI and pruned position

txpool/config.go, txpool/txpool.go, txpool/txpool_test.go
For better clarity, `ConsumptionBlocks` has been renamed to `ConsumptionWindow`. This change implies that consumption is measured within a specific window.
=> chore(txpool): rename ConsumptionBlocks to ConsumptionWindow

config/example_config.toml, state/state.go, store/block.go, store/interface.go, store/mock.go, store/store.go, store/store_test.go, txpool/config.go, txpool/config_test.go, txpool/interface.go, txpool/mock.go, txpool/txpool.go, txpool/txpool_test.go
Add estimated minimum and consumption fee
- Resolves #1543 #1544 #1545
=> feat(txpool): add consomptional fee model

cmd/cmd.go, cmd/cmd_test.go, cmd/daemon/init.go, cmd/gtk/startup_assistant.go
In these changes, we create 1 reward address (ed25519) instead 7-32 addresses for all validators when initializing a node.
- Fixes #1556
=> feat(wallet): create single ed25519 reward address for all validators

cmd/gtk/utils.go
This PR changes `transactions` to `transaction` for pacviewer link in GUI.
- https://github.com/pactus-project/pactus/issues/1569
=> fix(gtk): change transactions to transaction in tx link

cmd/gtk/dialog_wallet_create_address.go
Fix duplicate create new address by press `Enter`.
=> fix(gtk): prevent duplicate address on enter signal in create modal

consensus/consensus.go
This PR changes the timeout log level to `Debug` for better debugging.
=> chore(consensus): change Timeout log level to Debug

go.mod, go.sum, state/state.go, util/persistentmerkle/merkle.go, util/persistentmerkle/merkle_test.go
This PR addresses a panic occurring on 32-bit operating systems, including Raspberry Pi devices running 32-bit ARM OS.  
The root cause of the issue lies in the varying word sizes used in the `big.Int` implementation across different operating systems. A word is defined as an `int` in the `big.Int` implementation. Therefore, on 32-bit operating systems, each word is 32 bits, while on 64-bit systems, it is 64 bits.  
Since we use [kilic/bls12-381](https://github.com/kilic/bls12-381) in the wallet, this issue affects us directly. The problem has been addressed in their repository [here](https://github.com/kilic/bls12-381/pull/31). However, the repository is currently unmaintained. The ultimate solution would be to replace it with the [gnark-crypto](https://github.com/consensys/gnark-crypto) …
=> fix(crypto, state): resolve panic on 32-bit OSes

consensus/log/log_test.go, consensus/voteset/binary_voteset.go, consensus/voteset/block_voteset.go, types/vote/vote_type.go
This PR checks the vote signature and verifies the vote only if it has not been verified before and does not already exist. This approach prevents redundant verification of existing votes.
=> fix(consensus): ignore vote verification of existing votes

sync/firewall/errors.go, sync/firewall/firewall.go
This PR adds a check to determine if a bundle is expired. If it is, the connection to the sender peer will be closed. This helps prevent replay attacks where an attacker attempts to inject expired messages into the network.
=> feat(sync): check expired bundles

.github/workflows/releaser.yml
In this PR the cosign issue in releaser has been fixed. This issued happened because of conflict in upload-artifact and download-artifact versions.
See this doc: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md#which-versions-of-the-artifacts-packages-are-compatible
=> fix(release): upgrade upload-artifact to v4

network/gossip.go
Restore default message queue size for pubsub, it was set much higher the default value.
=> fix(network): restore default message queue size in PubSub module

cmd/gtk/dialog_about.go, cmd/gtk/main.go
This PR fixes a panic on Windows when the node can't start due to issue on loading logo pixbuf.
=> fix(gtk): fix panic on Windows 11 when laoding Pactus logo

cmd/gtk/assets/ui/widget_node.ui
This PR fixes a missing colon on connection label.
=> fix(gtk): fix missing colon on connection label

config/example_config.toml, sync/firewall/firewall.go, sync/firewall/firewall_test.go, sync/sync.go, tests/main_test.go, util/logger/config.go, util/logger/logger.go
This PR includes support for the firewall module in the logger.
- Fixes #1631
=> feat(config): add firewall module to logger config

committee/committee_test.go, consensus/consensus_test.go, consensus/voteset/voteset_test.go, genesis/genesis_test.go, sandbox/sandbox_test.go, state/lastinfo/last_info_test.go, store/account_test.go, store/mock.go, store/validator_test.go, sync/sync_test.go, types/account/account_test.go, types/certificate/block_certificate_test.go, types/proposal/proposal_test.go, types/validator/validator_test.go, util/testsuite/testsuite.go, wallet/wallet_test.go
This PR aims to simplify and improve tests by refactoring the `GenerateTestAccount` and `GenerateTestValidator` methods. These methods now accept options to construct test accounts and validators with optional parameters.
- Fixes #1606
=> test(types): refactor account and validator tests

consensus/consensus.go, consensus/cp.go, consensus/cp_decide.go
Refcator strong termination for change-proposer phase
=> fix(consensus): refcator strong termination for change-proposer phase

cmd/gtk/assets/ui/widget_node.ui, cmd/gtk/dialog_about.go, cmd/gtk/main.go
Some users are reported they GUI panics while loading the Pactus logo (SVG)
=> fix(gtk): panic on windows 11 and mac

www/grpc/utils.go, www/grpc/utils_test.go
Fix for the issue : [Sign and verify message by ed25519](https://github.com/pactus-project/pactus/issues/1549)
=> feat(grpc): support Ed25519 message signing and verification

www/zmq/config.go, www/zmq/config_test.go, www/zmq/publisher_block_info.go, www/zmq/publisher_raw_block.go, www/zmq/publisher_raw_tx.go, www/zmq/publisher_raw_tx_test.go, www/zmq/publisher_test.go, www/zmq/publisher_tx_info.go, www/zmq/server_test.go, www/zmq/topic.go, www/zmq/topic_test.go
Add publisher raw tx
- Fixes #1657
=> feat(zeromq): add publisher raw tx

util/io.go
Fix invalid cross-device link on renaming.
- Fixes #1579
=> fix(util): add manually copy to prevent invalid cross-device link

version/version.go
=> chore: bumping version to 1.7.1

consensus/prepare.go
Schedule another timeout to retry querying for the proposal or votes.
This ensures that delayed or missing data doesn't cause the process to stall.
- Fixes #1697
=> fix(consensus): schedule timeout to retry querying for the proposal or votes

network/network_test.go
> Added unit test for loadOrCreateKey, tested with the following cases:
1. Valid Private Key created
2. Invalid Private Key in existing file
3. Input supplied with directory instead of file path
4. Input supplied with invalid file path
> Nil
Fixes # (issue)
- Increased Unit Test Coverage from 76.6% to 82.1% in `network_test.go`
=> test(network): added unit test for loadOrCreateKey

sync/bundle/bundle.go, sync/bundle/bundle_test.go, sync/firewall/firewall.go, sync/firewall/firewall_test.go
This PR drops messages with mismatched consensus height instead of banning the peers,
to support nodes running older versions.
=> fix(sync): drop messages with mimatched consensus height

util/bech32m/bech32m.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
=> refactor(util): use the built-in max/min to simplify the code

cmd/shell/main.go, cmd/shell/main_test.go, util/shell/shell.go, util/shell/shell_test.go
This PR changes the command name from "shell" to "interactive" (issue #1717)for a more accurate representation of the functionality. The command provides an interactive CLI for interacting with the Pactus blockchain.
- Renamed the shell command to "interactive" throughout the codebase
- Updated welcome message to "Welcome to PactusBlockchain interactive mode"
- Modified unit tests to reflect the new command name
- Maintained all existing functionality while using the new name
- Verified basic interactive mode functionality
- Checked command completion works correctly
- Tested all blockchain/network/transaction/wallet service commands
- Ran all unit tests to ensure they pass with new naming
=> refactor(shell): rename shell command to interactive

util/bip39/bip39.go
In the Go 1.21 standard library, a new function has been introduced that enhances code conciseness and readability. It can be find  [here](https://pkg.go.dev/slices@go1.21.1#Equal).
Fixes # (issue)
=> refactor(util): use slices.Equal to simplify code

cmd/daemon/import.go, util/downloader/downloader.go
Prevent a panic on progress bar when a chunk was re-downloaded.
Fixes #1848
=> fix(cmd): prevent panic on redownloading chunk

util/testsuite/testsuite.go
Try to fix this random test failure in Windows:
```
libp2p error: failed to listen on any addresses: [listen udp4 127.0.0.1:57621: bind: An attempt was made to access a socket in a way forbidden by its access permissions.]
```
=> test(network): fix random failure on network tests for Windows

consensus/voteset/binary_voteset.go, consensus/voteset/block_voteset.go, consensusv2/voteset/binary_voteset.go, consensusv2/voteset/block_voteset.go, wallet/vault/vault.go
There is a [new function](https://pkg.go.dev/maps@go1.21.1#Copy) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor(other): use maps.Copy for cleaner map handling
