pactus-project/pactus

block/block.go, block/block_test.go, block/header.go, block/txs.go, block/txs_test.go, libs/merkle/merkle_test.go, message/txs.go, state/execution.go, state/state.go, store/store_test.go, store/tx.go, sync/dispatch.go, sync/sync_test.go, tx/committed_tx.go, tx/committed_tx_test.go, tx/receipt.go, tx/receipt_test.go, tx/tx.go, tx/tx_test.go, txpool/mock.go, txpool/pool.go, txpool/pool_test.go, www/capnp/block.go, www/capnp/transaction.go, www/http/http_test.go, www/http/transaction.go
- TxHashe renamed to TxID
- - TxID is hash of SignBytes (excluding public key and signature)
=> Rename TxHash to TxID

consensus/consensus_test.go, consensus/hrs/hrs_test.go, execution/execution_test.go, genesis/genesis_test.go, message/messages.go, sandbox/sandbox_test.go, state/last_info.go, state/last_info_test.go, state/merkel_test.go, state/merkle.go, state/state.go, state/state_test.go, sync/fetch.go, sync/stats/stats.go, sync/sync_test.go, www/http/http_test.go
- Recalculating genesis state on loading time
=> Recalculating genesis state

consensus/consensus_test.go, crypto/signer.go, sync/network_api.go, tests/account_test.go, tests/block_test.go, tests/main_test.go, tests/validator_test.go, www/capnp/account.go, www/capnp/server.go, www/capnp/validator.go
Adding system test for getting block data
=> Adding system tests

block/block_test.go, consensus/consensus.go, message/message_test.go, message/messages.go, sync/fetch.go, util/slice.go, util/slice_test.go
GZip message payload if it is greater than 0124 bytes
=> Gzip message payload

consensus/commit_test.go, consensus/consensus_test.go, consensus/height_test.go, consensus/precommit_test.go, consensus/prepare_test.go, consensus/propose.go, consensus/propose_test.go
- When there is no quorum for first round, ignore proposal for the second round
=> Check proposal for current round

cmd/zarb/init.go, consensus/consensus.go, consensus/consensus_test.go, consensus/height.go, consensus/height_test.go, consensus/pending_votes.go, consensus/pending_votes_test.go, consensus/propose.go, consensus/propose_test.go, genesis/genesis.go, genesis/genesis_test.go, logger/config.go, node/node_test.go, state/last_info_test.go, state/state.go, state/state_test.go, state/validation_test.go, tests/main_test.go, validator/validator_set.go, validator/validator_set_test.go, vote/vote_set.go, vote/vote_set_test.go
- Copy validators and assign them to vote set in each height
- Add a test for the situation in which consensus is behind the state and the validator set has changed
=> Copy validators 

README.md, cmd/zarb/init.go, cmd/zarb/key/change_auth.go, cmd/zarb/key/inspect.go, cmd/zarb/key/sign.go, cmd/zarb/key/verify.go, cmd/zarb/main.go, cmd/zarb/start.go, cmd/zarb/tx/bond-tx.go, cmd/zarb/version.go
- Add `tx` command 
- Add `bond` sub command
=> Add bond-tx command

block/block_test.go, consensus/config.go, consensus/consensus.go, consensus/consensus_test.go, consensus/height_test.go, consensus/precommit_test.go, consensus/propose.go, consensus/propose_test.go, consensus/round_test.go, state/last_info_test.go, state/state.go, state/state_test.go, state/validation_test.go, tests/transaction_test.go, util/time_test.go
=> Validate block time

sync/sync.go, sync/sync_test.go
- Only active validators (the one are in the set) can send query messages
- Anyone can respond query messages
=> Respond query message even the validator is not in the set

.github/workflows/ubuntu.yml, cmd/zarb/init.go, network/bootstrap.go, network/config.go
- Adding new config for Maximum connection threshold
=> Adding maximum threshold config

sync/consensus_sync_test.go, sync/network_api/mock.go, sync/state_sync_test.go, sync/sync.go, sync/sync_test.go
- Request for the last block if a node is behind the network by one block
=> Last block

consensus/pending_votes_test.go, vote/vote_set.go, vote/vote_set_test.go
- Remove the duplicated vote if detected
=> Remove duplicated vote if detected

crypto/private_key.go, crypto/private_key_test.go, crypto/public_key.go, crypto/public_key_test.go, crypto/signature.go, crypto/signature_test.go, www/http/blockchain.go, www/http/server.go
- JSON marshaling for empty public key
=> Enable JSON-marshaling for empty public key

sandbox/sandbox.go, sandbox/sandbox_test.go, state/last_info.go, state/state.go, state/state_test.go, store/validator.go, store/validator_test.go
- For existing validator, stake function returned old value. Fixed here
=> Updating validator map  

cmd/zarb/main.go
=> Add send command

block/txs.go, block/txs_test.go, consensus/precommit.go, state/execution.go, state/last_info.go, state/state.go, store/tx.go, sync/cache/cache.go, sync/consensus_sync.go, sync/message/factory.go, sync/state_sync.go, sync/sync.go, sync/sync_test.go, tx/committed_tx.go, tx/receipt.go, tx/tx.go, txpool/interface.go, txpool/mock.go, txpool/pool.go, txpool/pool_test.go, www/capnp/block.go
- Define ID for transactions
- Broadcast all the transaction inside block after proposing
=> Broadcast all transaction in proposed block

consensus/height.go, consensus/pending_votes_test.go, state/mock.go, state/state_test.go, sync/firewall/firewall_test.go, sync/sync_test.go, validator/validator.go, validator/validator_set.go, validator/validator_set_test.go, vote/proposal_test.go, vote/vote_set_test.go, www/http/http_test.go
- Using list instead of slice for validator set
- Check oldest validator based on last height it joined the set
- Update tests
=> Update round robin alghorithm

www/grpc/account.go, www/grpc/account_test.go
* Added the new grpc GetAccount method.
* Added GetAccount test case.
=> added the grpc get account method

consensus/commit.go, consensus/commit_test.go, consensus/consensus.go, consensus/consensus_test.go, consensus/height.go, consensus/precommit.go, consensus/propose_test.go, consensus/round.go
- Check if timeout events are in the same height of consensus, otherwise ignore the,
=> Check height in consensus timeout event

consensus/height.go, consensus/round.go, consensus/round_test.go, execution/execution_test.go, execution/executor/sortition.go, execution/executor/sortition_test.go, sandbox/mock.go, state/state.go, sync/sync.go, tests/main_test.go, tests/transaction_test.go, txpool/pool.go
- Make sure integration test are passed
=> Integration test

.github/codecov.yml, consensus/round.go, consensus/round_test.go, tests/main_test.go
- Check if we enter new round for the second time and prevent it + test
=> Prevent duplicated round entry

sandbox/sandbox_test.go, state/last_info/last_info_test.go, state/mock.go, state/state.go, store/account.go, store/account_test.go, store/block.go, store/block_test.go, store/interface.go, store/mock.go, store/store.go, store/store_test.go, store/tx.go, store/validator.go, store/validator_test.go, sync/cache/cache_test.go, www/http/http_test.go
- implemented batch writing into store.
- remove SaveBlock method returning error, panic instead if SaveBlock hit error.
=> Batch writing

README.md, cmd/cmd.go, cmd/zarb/init.go, cmd/zarb/key/README.MD, cmd/zarb/key/generate.go, cmd/zarb/key/inspect.go, cmd/zarb/key/verify.go, consensus/config.go, genesis/mainnet.go, keystore/key/encrypted.go, keystore/key/encrypted_test.go, keystore/key/key.go, network/bootstrap.go, network/config.go, network/mdns.go, sync/config.go
- Adding mainnet opt to init command
=> Mainnet opt

block/certificate.go, committee/committee.go, committee/committee_test.go, committee/interface.go, execution/executor/sortition.go, network/network.go, node/node.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, sortition/proof.go, sortition/seed.go, sortition/sortition.go, sortition/sortition_test.go, sortition/vrf.go, sortition/vrf_test.go, state/execution_test.go, state/facade.go, state/last_info/last_info.go, state/last_info/last_info_test.go, state/mock.go, state/state.go, state/state_test.go, tests/main_test.go, tests/transaction_test.go, tx/tx.go, tx/tx_test.go, www/grpc/validator_test.go
- Sortition evaluated based on pool stake  
- Check if the oldest validator had chance to propose a block
=> Calculating pool stake for sortition to be more fair

consensus/prepare.go
=> consensus: Decide after querying proposal

consensus/consensus.go, consensus/consensus_test.go, consensus/precommit.go, consensus/prepare.go
- Not broadcasting prepare & precommit votes for previous round
- Broadcasting proposer change votes for previous round
- Update test
=> consensus: Sending proposer changes votes for previous round

consensus/commit_test.go, consensus/consensus_test.go, consensus/propose_test.go, go.mod, state/state.go, state/state_test.go, util/time.go, util/time_test.go
- Rounding time to down
- Tolerate proposed block time if it is not more that 10 second off
=> consensus: Rounding down the proposed block time

state/state.go, state/state_test.go, state/validation.go, state/validation_test.go
- Updating test for detecting fork
- Panic when a fork is detected
=> state: Panic on detecting fork

block/certificate.go, committee/committee.go, committee/committee_test.go, committee/interface.go, execution/executor/sortition.go, genesis/genesis_test.go, genesis/testnet.go, network/network.go, node/node.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, sortition/proof.go, sortition/seed.go, sortition/sortition.go, sortition/sortition_test.go, sortition/vrf.go, sortition/vrf_test.go, state/execution_test.go, state/facade.go, state/lastinfo/last_info.go, state/lastinfo/last_info_test.go, state/mock.go, state/state.go, state/state_test.go, tests/main_test.go, tests/transaction_test.go, tx/tx.go, tx/tx_test.go, www/grpc/validator_test.go
- Sortition evaluated based on pool stake
- Check if the oldest validator had chance to propose a block
=> consensus: Evaludating sortition based on pool stake

sync/handler_latest_block_request_test.go, sync/sync_test.go
- Decreasing LatestBlockInterval to 20 for sync tests
=> Decrease LatestBlockInterval number for tests

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
- Adding templates for Issues
- Adding template for Pull Requests
- Adding Contributing doc
=> GitHub templates

CHANGELOG.md, execution/executor/bond.go, execution/executor/bond_test.go, sandbox/mock.go, validator/validator.go
Updating last bonding height for validators upon executing bond transactions
=> Updating last bonding height for validators

README.md
This PR adds Contributor Covenant badge to the readme
No issue is related to this PR.
=> Adding Contributor Covenant badge

.gitignore, cmd/zarb/init.go
Merging duplicated codes for generating validator key. 
Also the network name for local network changed to prevent any possible conflict with mainnet or testnet networks.
=> Merge duplicated codes for generating validator key

.github/workflows/testing.yml
lighten test Pipe and only run go15 on PRs and go16 on merges
=> Test lighten

sandbox/sandbox.go, state/validation_test.go, sync/message/payload/aleyk_test.go, sync/message/payload/block_announce.go, sync/message/payload/block_announce_test.go, sync/message/payload/download_request_test.go, sync/message/payload/download_response.go, sync/message/payload/download_response_test.go, sync/message/payload/heart_beat_test.go, sync/message/payload/latest_blocks_request_test.go, sync/message/payload/latest_blocks_response_test.go, sync/message/payload/proposal_test.go, sync/message/payload/query_proposal_test.go, sync/message/payload/query_transactions_test.go, sync/message/payload/query_votes_test.go, sync/message/payload/salam_test.go, sync/message/payload/transactions_test.go, sync/message/payload/vote_test.go
This PR add tests for all the message payloads.
Fixing #169
=> Update test for messages. Fixing #169

.gitignore, config/config.go, config/config_test.go, consensus/config.go, go.mod, go.sum, logger/config.go, network/config.go, state/config.go, store/config.go, sync/config.go, txpool/config.go, www/capnp/config.go, www/grpc/config.go, www/grpc/gateway.go, www/http/config.go
* Added the test case to config.
* Remove unwanted tag in comment
* Added few toml comments to sync config and config file
=> Comment config

www/grpc/config.go, www/grpc/gateway.go
=> grpc: enable CORS for gRPC

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Comment description paragraph for Github templates
=> Update Github templates

CHANGELOG.md, version/version.go
=> Downgrade the version

CHANGELOG.md, crypto/address.go, crypto/address_test.go, crypto/bls/public_key_test.go, crypto/bls/signature_test.go
Renaming hrp to 'zc' for address string
=> Updating hrp for address string

crypto/hash/hash.go, go.mod, go.sum
Replacing blake2b package with https://pkg.go.dev/golang.org/x/crypto
=> Replacing blake2b package

.github/workflows/coverage.yml, .github/workflows/deadlock.yml, .github/workflows/linting.yml, .github/workflows/releaser.yml, .github/workflows/testing.yml, Makefile
Updating Go version for Github actions
Should fix linting issue
=> Updating Go version in Github actions

network/mdns.go, network/network.go
Removing legacy mDNS which is going to be deprecated soon
Closes #238
=> Removing legacy mDNS

.github/workflows/deadlock.yml, .github/workflows/docker.yml, .github/workflows/testing.yml, consensus/mock.go, sync/handler_download_responce_test.go
Adding data race detection test
=> Updating github workflows

tests/main_test.go, txpool/config.go, txpool/config_test.go, txpool/pool.go, txpool/pool_test.go
Removing channel and use ticker to check for querying missed transaction
=> Using ticker for Query transaction

Makefile
* Fix the herumi bls issue for mac os.
=> Fix the hermui issue in for mac os

block/block.go, block/header.go, sortition/seed.go, sortition/seed_test.go, sortition/sortition.go, sortition/sortition_test.go, sortition/vrf.go, state/lastinfo/last_info.go, state/lastinfo/last_info_test.go, state/state.go
Renaming `sortition.Seed` to `sortition.VerifiableSeed`
=> Renaming seed to verifiable_seed

execution/executor/bond.go, execution/executor/bond_test.go, execution/executor/send.go, execution/executor/send_test.go, execution/executor/sortition.go, execution/executor/sortition_test.go, execution/executor/unbond.go, execution/executor/unbond_test.go, execution/executor/withdraw.go, execution/executor/withdraw_test.go, libs/linkedmap/linkedmap.go, libs/linkedmap/linkedmap_test.go, sandbox/mock.go, state/state.go, tx/payload/bond.go, tx/payload/send.go, tx/payload/sortition.go, tx/payload/unbond.go, tx/payload/withdraw.go, txpool/config.go, txpool/config_test.go, txpool/interface.go, txpool/mock.go, txpool/pool.go, txpool/pool_test.go
- Adding sub-pools to transaction pool
- Appending transactions to the sub-pool based on payload type
=> Adding sub-pools to transaction pool

.github/workflows/coverage.yml, .github/workflows/deadlock.yml, .github/workflows/docker.yml, .github/workflows/linting.yml, .github/workflows/testing.yml
Prevent running Github Action on push to branches other than main
=> Updating workflows

network/bootstrap.go, network/gossip_test.go, network/network_test.go, network/stream_test.go
Network test randomly failed. This patch try to fix it.
=> Fixing a random failure in network tests

cmd/zarb/init.go, genesis/genesis_test.go, genesis/testnet.go
Adding genesis file for the new testnet
=> Adding genesis file for new testnet

crypto/bls/bls_test.go, crypto/bls/signature_test.go
Adding new test for BLS aggregated signature
=> Adding new test for BLS aggregated signature

sync/bundle/message/hello.go, sync/handler_hello.go, sync/handler_hello_test.go, sync/sync.go
Renaming need_response flag to hello_ack
=> Renaming need_response flag to hello_ack

cmd/cmd.go, cmd/zarb/init.go, cmd/zarb/key/generate.go, cmd/zarb/start.go, crypto/bls/bls.go, crypto/bls/signature_test.go, keystore/key/encrypted.go, keystore/key/encrypted_test.go, keystore/key/key.go, keystore/key/key_test.go, node/node_test.go, store/config.go, store/config_test.go
- Removing `GenerateRandomKey` method
- Generating mnemonics by initializing the workspace
=> Generating mnemonics by initializing the workspace

crypto/bls/private_key.go, crypto/bls/private_key_test.go, keystore/key/key_test.go, sortition/vrf.go
KeyGen based on spec: https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-00#section-2.3
=> Generating key based on spec

block/certificate_test.go, crypto/address.go, crypto/address_test.go, crypto/bls/bls_test.go, crypto/bls/private_key.go, crypto/bls/private_key_test.go, crypto/bls/public_key.go, crypto/bls/public_key_test.go, crypto/bls/signature.go, crypto/bls/signature_test.go, crypto/hash/hash.go, crypto/hash/hash_test.go, crypto/hash/stamp.go, crypto/hash/stamp_test.go, crypto/private_key.go, crypto/public_key.go, genesis/genesis.go, genesis/genesis_test.go, keystore/key/encrypted.go, tx/tx.go
- Removing `UnmarshalJSON` methods
- Adding zero values to SanityCheck (for crypto)
=> Removing UnmarshalJSON methods

execution/executor/sortition.go, execution/executor/sortition_test.go
The PR checks if validator is in committee and committee has free seats.
The Sortition transaction will be rejected to be inside the block
=> Check if validator is in committee

block/block.go, execution/execution.go, execution/execution_test.go, genesis/genesis_test.go, genesis/testnet.go, param/param.go, sandbox/interface.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, state/state.go, tx/tx.go, tx/tx_test.go
Removing MaximumMemoLength and MaximumTransactionPerBlock from the consensus parameters
=> Updating consensus parameters

www/grpc/block.go, www/grpc/block_test.go
* updated the transaction details in gRPC function `get_block.
* added the test case.
If this PR closes any issue, mention here.
=> changes made in grpc `get_block` and test case

www/grpc/transaction.go, www/grpc/transaction_test.go
* Checking the signature and public key for mint base transaction.
=> check signature is not empty

block/certificate.go, block/certificate_test.go
Adding `CBOR` marshalling to `certificate`
=> Adding CBOR marshaling to certificate

network/interface.go, network/mock.go, network/stream.go, sync/sync.go, www/grpc/transaction.go
Closing read and write stream.
=> Converting stream Reader to ReadCloser

Makefile
Adding `ineffassign` linter and enabling more linters
=> Adding ineffassign linter

.github/workflows/releaser.sh, .gitignore, Makefile, cmd/daemon/init.go
Fixing linting and releaser issues
=> Fixing linting and releaser issues

.github/workflows/releaser.yml, Dockerfile
Installing 7z to pack the files inside releaser
=> Installing 7z

.github/workflows/releaser.yml, Makefile
Updating releaser for windows (creating bundle for GUI)
=> Updating releaser for windows

network/gossip_test.go, network/network_test.go, network/stream_test.go
Fixing a random failure in network tests
=> Fix a random failure in network tests

cmd/daemon/init.go, cmd/daemon/start.go, cmd/gtk/main.go, cmd/gtk/startup_assistant.go, crypto/address.go, crypto/address_test.go, wallet/store.go, wallet/vault/vault.go, wallet/vault/vault_test.go, wallet/wallet.go
For testnet addresses we use `tzc` for HRP
=> New HRP for testnet addresses

cmd/gtk/widget_node.go
Fix GUI upon syncing block the display of block left.
=> fixing blocksleft for GUI.

cmd/cmd.go, cmd/daemon/init.go, cmd/daemon/start.go, cmd/gtk/model_wallet.go, cmd/wallet/address.go, cmd/wallet/create.go, cmd/wallet/main.go, cmd/wallet/recover.go, cmd/wallet/tx.go, go.mod, go.sum, state/state.go, store/config.go, store/store_test.go, wallet/errors.go, wallet/store.go, wallet/tx_maker.go, wallet/vault/argon2.go, wallet/vault/argon2_test.go, wallet/vault/errors.go, wallet/vault/vault.go, wallet/vault/vault_test.go, wallet/wallet.go, wallet/wallet_test.go
- Wallet now can support other curves than BLS signature. (for future use)
- Using [promptui](https://github.com/manifoldco/promptui) for interactive CLI
- CLI new feature: Change wallet password
- CLI new feature: Set label
- Refactoring transaction builder
=> Wallet supports multi curves

cmd/gtk/model_wallet.go, cmd/gtk/widget_node.go, cmd/gtk/widget_wallet.go
Adding a basic timer for wallet widget
=> Adding a basic timer for wallet widget

consensus/change_proposer.go, consensus/change_proposer_test.go, consensus/config.go, consensus/config_test.go, consensus/consensus.go, consensus/consensus_test.go, consensus/height_test.go, consensus/interface.go, consensus/mock.go, consensus/precommit.go, consensus/precommit_test.go, consensus/prepare.go, consensus/prepare_test.go, consensus/propose.go, network/gossip.go, node/config/example_config.toml, state/state.go, sync/cache/cache.go, sync/cache/cache_test.go, sync/handler_block_announce.go, sync/handler_blocks_response.go, sync/handler_hello.go, sync/handler_proposal.go, sync/handler_proposal_test.go, sync/handler_query_proposal.go, sync/handler_query_proposal_test.go, sync/handler_query_votes.go
Keeping proposal inside the cache has no point. We don't need to cache it.
=> Removing proposal from sync cache

wallet/vault/argon2.go, wallet/vault/argon2_test.go, wallet/vault/utils.go
=> Rename MAC method

cmd/daemon/start.go, cmd/gtk/main.go, cmd/wallet/address.go, cmd/wallet/create.go, cmd/wallet/main.go, cmd/wallet/recover.go, cmd/wallet/tx.go, wallet/errors.go, wallet/tx_maker.go, wallet/wallet.go, wallet/wallet_test.go
=> Adding offline wallet

cmd/daemon/start.go, cmd/gtk/main.go, cmd/wallet/address.go, cmd/wallet/create.go, cmd/wallet/main.go, cmd/wallet/recover.go, cmd/wallet/tx.go, wallet/errors.go, wallet/tx_maker.go, wallet/wallet.go, wallet/wallet_test.go
=> Offline wallet

cmd/gtk/assets/ui/dialog_about.ui, cmd/gtk/assets/ui/dialog_about_gtk.ui, cmd/gtk/assets/ui/dialog_label.ui, cmd/gtk/dialog_about.go, cmd/gtk/dialog_about_gtk.go, cmd/gtk/dialog_label.go, cmd/gtk/dialog_password.go, cmd/gtk/main.go, cmd/gtk/main_window.go, cmd/gtk/startup_assistant.go, cmd/gtk/utils.go, cmd/gtk/widget_wallet.go
By applying this PR, users are able to update the address label.
=> GUI: Update label dialog

consensus/change_proposer.go, consensus/commit.go, consensus/consensus.go, consensus/consensus_test.go, consensus/height.go, consensus/height_test.go, consensus/log/log.go, consensus/log/log_test.go, consensus/precommit.go, consensus/prepare.go, consensus/propose.go, consensus/state.go, consensus/voteset/voteset.go, consensus/voteset/voteset_test.go
By removing height from the consensus logs we reduce the code complexity
=> Removing height from the consensus logs

sortition/sortition_test.go, types/crypto/bls/bls_test.go, types/crypto/bls/private_key.go, types/crypto/bls/private_key_test.go, types/crypto/bls/public_key.go, types/crypto/bls/public_key_test.go
Serializing public key with bech32
=> Serializing public key with bech32

www/grpc/gateway.go
Fixing potential slowloris attack (G112)
=> Fixing potential slowloris attack

wallet/hdkeychain/extendedkey.go, wallet/hdkeychain/extendedkey_test.go
Supporting [BIP0032](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)  Hierarchical Deterministic Wallets for BLS signature
=> HD Key chain

cmd/daemon/start.go, cmd/gtk/main.go, types/crypto/address.go, types/crypto/bls/private_key.go, types/crypto/bls/public_key.go, types/crypto/bls/public_key_test.go, types/crypto/crypto.go, types/genesis/genesis_test.go, types/genesis/testnet.json, wallet/hdkeychain/extendedkey.go, wallet/wallet.go
=> Definign HRPs for testnet

.github/workflows/gui.yml, cmd/gtk/assets/ui/dialog_address_details.ui, cmd/gtk/assets/ui/dialog_address_label.ui, cmd/gtk/assets/ui/dialog_wallet_change_password.ui, cmd/gtk/assets/ui/dialog_wallet_password.ui, cmd/gtk/assets/ui/dialog_wallet_show_seed.ui, cmd/gtk/dialog_address_change_password.go, cmd/gtk/dialog_addresss_details.go, cmd/gtk/dialog_addresss_label.go, cmd/gtk/dialog_wallet_password.go, cmd/gtk/dialog_wallet_show_seed.go, cmd/gtk/widget_wallet.go
=> GTK: Address details dialog

store/store.go, store/store_test.go, sync/sync.go
Moving consensus to the next height
=> Fixing localnet issue

cmd/gtk/assets/ui/dialog_address_private_key.ui, cmd/gtk/dialog_address_change_password.go, cmd/gtk/dialog_addresss_private_key.go, cmd/gtk/utils.go, cmd/gtk/widget_wallet.go
Adding new GTK dialog to show the private key
=> GTK: Private key dialog

execution/execution.go, execution/execution_test.go, execution/executor/bond.go, execution/executor/bond_test.go, execution/executor/send.go, execution/executor/send_test.go, execution/executor/sortition.go, execution/executor/sortition_test.go, execution/executor/unbond.go, execution/executor/unbond_test.go, execution/executor/withdraw.go, execution/executor/withdraw_test.go, sandbox/interface.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, store/store.go, sync/sync.go, types/genesis/genesis_test.go, types/genesis/testnet.json, types/param/param.go
A few sentences describing the the pull request.
* Adding Maximum stake consensus parameter.
=> Adding Maximum stake consensus parameter

wallet/vault/vault.go, wallet/vault/vault_test.go
* Removing empty labels from wallet.
=> Removing empty labels from wallet

.github/releasers/releaser_windows.sh, .github/workflows/coverage.yml, .github/workflows/deadlock.yml, .github/workflows/gui.yml, .github/workflows/linting.yml, .github/workflows/releaser.yml, .github/workflows/testing.yml
This PR includes these changes:
- libffi for Windows updated from version 7 to 8  (libffi-8.dll to libffi-7.dll). 
- Some action files used actions/checkout@v2, I update all actions to use v3.
- Also there is a mistake in go version in Linux releaser. 
Fixing issue #350
=> Updating libffi DLL

.github/workflows/gui.yml, .github/workflows/releaser.yml
Go compiler was missed from MinGW.
Fixing #350
=> Installing go for mingw compiler

Dockerfile
Updating alpine to 1.16 to support go1.18
=> Updating alpine

cmd/gtk/assets/icons/send.svg, cmd/gtk/assets/ui/dialog_address_details.ui, cmd/gtk/assets/ui/dialog_transaction_send.ui, cmd/gtk/assets/ui/main_window.ui, cmd/gtk/dialog_addresss_private_key.go, cmd/gtk/dialog_transaction_send.go, cmd/gtk/icons.go, cmd/gtk/main_window.go, cmd/gtk/model_wallet.go, cmd/gtk/utils.go, cmd/gtk/widget_node.go, cmd/gtk/widget_wallet.go, cmd/wallet/address.go, cmd/wallet/main.go, cmd/wallet/tx.go, util/utils.go, util/utils_test.go, wallet/tx_maker.go, wallet/wallet.go
* User can broadcast send transaction through GUI app
=> User can broadcast send transaction through GUI app

cmd/gtk/assets/ui/dialog_transaction_bond.ui, cmd/gtk/assets/ui/main_window.ui, cmd/gtk/dialog_transaction_bond.go, cmd/gtk/main_window.go
=>  Bond transaction dialog

.github/releasers/releaser_linux.sh, .github/releasers/releaser_macos.sh, .github/releasers/releaser_windows.sh, Dockerfile
Dockerfile still used Herumi that was removed at #382
=> Fixing docker issue

sync/handler_heart_beat_test.go, sync/sync_test.go
To make tests faster, we disable Hearbeat for most of the tests. 
Related to #164
=> Disabling heartbeat for tests

cmd/wallet/address.go, execution/executor/sortition.go, network/network.go, state/merkel_test.go, state/state.go, sync/firewall/firewall_test.go, sync/handler_block_announce.go, sync/handler_heart_beat_test.go, sync/handler_hello.go, sync/sync.go, wallet/grpc_client.go
- Enabling sending transaction from wallet-CL. 
- Updating some logs
- Fixing some typos
=> Sending transaction from wallet cli

.github/releasers/releaser_cli.sh
Binaries in windows packed without exe extension.
=> Adding exe extension for windows binaries

cmd/gtk/main.go, cmd/gtk/widget_node.go, cmd/gtk/widget_wallet.go, network/bootstrap.go
Fixing "Not responding" issue on windows
Related to: #403
=> gui: fixing not responding issue

sync/sync.go
joining consensus topic by starting sync
=> sync: joining consensus topic by starting sync

cmd/gtk/main.go, cmd/gtk/startup_assistant.go, cmd/gtk/widget_node.go
fixing sudden panic on Windows.
=> gui: fixing sudden panic on Windows

cmd/gtk/model_wallet.go, cmd/gtk/widget_wallet.go
fixing a sudden panic when the wallet has many addresses
=> gtk: fixing a sudden panic when the wallet has many addresses

cmd/gtk/assets/ui/widget_node.ui, cmd/gtk/widget_node.go
=> Show committee information

cmd/gtk/main.go, cmd/gtk/model_wallet.go, cmd/gtk/widget_node.go, cmd/gtk/widget_wallet.go
=> gui: fixing linting issue

www/http/block.go
From a brief test, this appears to bring in full information on transactions.
Closes #428
=> Request full information on block transactions in HTTP module

consensus/spec/README.md
Updating the README for TLA+ spec and adding the instruction to run TLC.
=> fix: updating tla+ readme

.github/workflows/semantic-pr.yml
Adding a new workflow to lint the PR titles.
=> ci: adding semantic PR workflow

types/block/block_test.go, types/block/certificate.go, types/block/certificate_test.go
Removing committers from the certificate hash.
=> fix: removing committers from the certificate hash

INSTALL.md, cmd/wallet/create.go, cmd/wallet/main.go, cmd/wallet/recover.go
Wallet path should specify for all the wallet commands.
=> fix: wallet path as argument

cmd/gtk/assets/ui/widget_node.ui, cmd/gtk/main.go, cmd/gtk/model_wallet.go, cmd/gtk/widget_node.go
This PR checks if the running node has any active consensus instances (validators in the committee).
=> fix(gui): check if the node has an active consensus instance

execution/execution_test.go, genesis/genesis_test.go, genesis/testnet.json, types/param/param.go, version/version.go
Updating genesis for Testenet-1 and bumping version to 0.10.0
=> chore: bumping version to 0.10.0

crypto/address.go, crypto/address_test.go, crypto/bls/bls_test.go, crypto/bls/private_key_test.go, crypto/bls/public_key_test.go, crypto/bls/signature_test.go
Updating crypto tests and check the error messages
=> test(crypto): updating tests

committee/committee_test.go
=> test: updating committee tests

cmd/cmd.go, cmd/daemon/init.go, cmd/daemon/main.go, cmd/daemon/start.go, cmd/gtk/main.go, consensus/log/messages.go, network/dht.go, network/gossip.go, store/account.go, store/block.go, store/validator.go
The password option has been added to the `start` command for both `daemon` and `gui`. 
To prevent any possible mistakes during the Mainnet launch, the working directory for the Testnet has been changed to `~/pactus/testnet`.
Fixing #472
=> fix: adding password option to the start commands

consensus/consensus.go, consensus/consensus_test.go, consensus/interface.go, consensus/manager_test.go, consensus/mock.go, util/slice.go, util/slice_test.go
Fixing a data race in tests.
Data race happened in consensus tests: https://github.com/pactus-project/pactus/actions/runs/5032734690/jobs/9026529760?pr=474
=> test: fixing a data race in tests

.github/ISSUE_TEMPLATE/bug_report.md
=> chore: updating the issue template

CHANGELOG.md, README.md, docs/releasing.md, version/version.go
=> chore: bumping version to 0.12.0

cmd/gtk/assets/ui/widget_node.ui
=> chore: Typo in GUI

committee/committee.go, committee/committee_test.go, committee/interface.go, execution/executor/bond.go, execution/executor/bond_test.go, execution/executor/transfer.go, execution/executor/unbond.go, network/mdns_test.go, sandbox/sandbox_test.go, types/validator/validator.go
Updating committee , sandbox and executor tests
=> test: updating tests

.github/releasers/pactus_downloader.sh, .github/releasers/releaser_cli.sh, .github/releasers/releaser_gui_linux.sh, .github/releasers/releaser_gui_macos.sh, .github/releasers/releaser_gui_windows.sh, .github/workflows/releaser.yml
Pactus Downloader is a simple script that helps users to download, verify and extract CLI packages.
=> chore: pactus downloader script

CHANGELOG.md, docs/releasing.md
=> chore: Releasing version 0.12.0

docs/releasing.md, version/version.go
=> chore: bumping version to 0.13.0

CHANGELOG.md
=> chore: releasing version 0.13.0

docs/releasing.md, version/version.go
=> chore: bumping version to 0.14.0

sync/peerset/peer_set_test.go
add missing tests for peerset
fixed https://github.com/pactus-project/pactus/issues/170
=> test: add missing tests for peerset

LICENSE
=> feat: License year update

.github/PULL_REQUEST_TEMPLATE.md
I changed the PR template, in this way when we use an issue number in PR that will link to issue
then the successful merge can close the issue.
=> feat: issue link to pr

LICENSE
Reverts pactus-project/pactus#570
Discussed [here](https://github.com/pactus-project/pactus/pull/570#issuecomment-1621148359)
=> chore: Revert "chore: License year update"

cmd/gtk/assets/css/style.css, cmd/gtk/assets/ui/dialog_address_details.ui, cmd/gtk/dialog_addresss_details.go, cmd/gtk/main_window.go, cmd/gtk/utils.go
I added a copy to the clipboard button for the public key and address in the address detail.
- Fixes #343
=> feat: copy to clipboard option for address and pubkey

go.mod, node/node.go
Blockchain is more correct instead of block chain.
=> chore: Blockchain typo

util/logger/logger.go, util/logger/logger_test.go
=> test: added test and fix keyvals

sync/peerset/peer.go, sync/peerset/peer_test.go
I wrote test for [peer.go](https://github.com/pactus-project/pactus/blob/cdf6d0957d79596e56355de3463cc029367b6e38/sync/peerset/peer.go#L12C28-L12C28)  file
- Fixes #615
=> test: adding tests for peer

.golangci.yml, wallet/store.go
enabling err check JSON linter
- Fixes #645
=> chore(linter): enable errchkjson

.golangci.yml, genesis/genesis.go, genesis/genesis_test.go, genesis/testnet.json, types/param/param.go
I enabeld `musttag` linter
- Fixes #647
=> chore(linter): enable musttag

.golangci.yml, cmd/daemon/init.go, cmd/gtk/utils.go, wallet/encrypter/encrypter.go, wallet/wallet.go
=> chore: enable wastedassign linter

config/config.go, config/config_test.go, config/example_config.toml, genesis/genesis.go, genesis/genesis_test.go, genesis/testnet.json, network/config.go, network/gossip_test.go, network/mdns_test.go, network/network.go, network/network_test.go, node/node.go, types/block/block_test.go
This PR updates the genesis document for the pre-testnet-2.
=> feat: updating genesis for pre-testnet-2

config/config.go, config/example_config.toml, network/config.go, www/grpc/config.go, www/http/config.go, www/nanomsg/config.go
I set the final ports in configs.
Test-net ports for test-net config function and main net ports in the example config and default configs.
- Fixes #593 
- Fixes #688
=> chore: Setting final ports

config/config.go, genesis/genesis.go, genesis/genesis_test.go, genesis/testnet.json, state/execution_test.go, state/state_test.go, tests/main_test.go, types/tx/tx.go, types/tx/tx_test.go
This PR updates genesis document for the pre-Testnte-2 network.
=> chore: updating Genesis doc for the Testnet-2

.gitignore, .golangci.yml, cmd/cmd.go, committee/committee.go, sortition/vrf.go, state/state.go, util/io.go
enable nonamedreturns linter
fix code which was highlighted by nonamedreturns
- Fixes #708
=> chore(lint): enable nonamedreturns linter

genesis/genesis_test.go, genesis/testnet.json
This PR updates the Genesis document for the Pre-Testnet-2.
=> chore: updating genesis for Pre-Testnet-2

cmd/daemon/init.go, cmd/gtk/startup_assistant.go, cmd/wallet/create.go, crypto/bls/hdkeychain/extendedkey.go, crypto/bls/hdkeychain/extendedkey_test.go, util/encoding/encoding.go, util/encoding/encoding_test.go, util/utils.go, wallet/encrypter/encrypter.go, wallet/encrypter/params.go, wallet/vault/utils.go, wallet/vault/utils_test.go, wallet/vault/vault_test.go, wallet/wallet.go, wallet/wallet_test.go, www/grpc/wallet_test.go
This PR implements the [PIP-11](https://pips.pactus.org/PIPs/pip-11).
=> feat: implementing pip-11

config/example_config.toml, util/logger/config.go, util/logger/logger.go, util/logger/logger_test.go
This PR addresses the problem of the logger level config not being applied.
=> fix: fixing logger level issue

consensus/consensus.go, consensus/prepare.go
Send query votes message if the query proposal timeout expires.
=> fix: send query votes message, if there is no proposal yet

wallet/addresspath/path.go, wallet/addresspath/path_test.go, wallet/vault/vault.go
fix unsorted addresses in wallet listing
- Fixes #714
=> fix!: unsorted addresses in wallet listing

config/example_config.toml, util/logger/config.go, util/logger/logger.go, util/logger/logger_test.go
=> fix(logger): invalid level parsing error

consensus/consensus.go, consensus/consensus_test.go, consensus/cp_test.go, consensus/interface.go, consensus/manager.go, consensus/manager_test.go, consensus/mock.go, consensus/precommit_test.go, consensus/prepare.go, consensus/prepare_test.go, consensus/propose_test.go, node/node.go, sync/bundle/bundle_test.go, sync/bundle/message/query_proposal.go, sync/bundle/message/query_proposal_test.go, sync/firewall/firewall_test.go, sync/handler_proposal_test.go, sync/handler_query_proposal.go, sync/handler_query_proposal_test.go, sync/sync.go, sync/sync_test.go, tests/main_test.go
This PR added an Anti-Entropy mechanism to the consensus.
It also simplified the manager tests.
=> fix(consensus): anti-entroy mechanism for the consensus

sync/handler_hello.go, sync/handler_query_proposal.go, sync/handler_query_proposal_test.go, sync/handler_query_votes.go, sync/handler_query_votes_test.go, sync/sync.go, sync/sync_test.go
This PR temporarily fixes the issue of query votes and proposals. It should be refactored in the future.
=> fix: fixing query votes and proposal issue

sync/firewall/firewall.go, sync/sync.go
This PR updates some logs to add information about the sender of bundles.
=> chore: updating some log messages

config/config.go, genesis/genesis_test.go, genesis/testnet.json, types/param/param.go
This PR updates the genesis file for the Testnet-2.
=> chore: updating genesis for Testnet-2

CHANGELOG.md, version/version.go
=> chore: releasing version 0.15.1

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 0.15.2

network/network.go, network/notifee.go
Updates some logs in the network module.
=> chore(networ): updating some logs in network

network/network.go, network/utils.go
Calculate logarithm scale for the network limits.
=> chore(networ): log-scale for network limit

network/dht.go, network/gossip.go, network/network.go
This PR enables Peer Exchange for bootstrappers.
=> fix(network): enabling peer exchange for bootstrappers

config/config.go
add community bootstrap nodes to testnet config
=> feat: add community bootstrap nodes to testnet config

docs/patching.md, version/version.go
=> chore: bumping version to 0.15.3

consensus/voteset/vote_box.go, consensus/voteset/vote_box_test.go
This PR prevents the increase of vote box power for duplicated votes.
=> fix(consensus): not increase the vote-box power on duplicated votes

network/dht.go, network/mdns.go, network/mdns_test.go, network/network.go, network/network_test.go, network/notifee.go, network/peermgr.go
This PR refactors peer manager and updates the network test.
=> refactor(network): refactoring peer manager

network/network.go, network/notifee.go, network/peermgr.go, network/stream.go
This PR redefines the network limits based on the maximum and minimum connections specified in the config.
=> fix(network): redefine the network limits

CHANGELOG.md, config/config.go, docs/releasing.md, version/version.go
=> chore: releasing version 0.16.0

docs/patching.md, version/version.go
=> chore: bumping version to 0.16.2

config/config.go, config/config_test.go, config/example_config.toml, consensus/consensus_test.go, network/config.go, network/config_test.go, network/dht.go, network/gater.go, network/mdns_test.go, network/network.go, network/network_test.go, network/notifee.go, network/peermgr.go, network/stream.go, network/utils.go, network/utils_test.go, sync/handler_blocks_response_test.go, sync/sync_test.go, tests/main_test.go, util/logger/logger.go, util/testsuite/logger.go
This PR stop creating transient connection when new stream fails.
=> fix(network): no transient connection

config/config.go
=> chore: change bootstrap address

CHANGELOG.md, CONTRIBUTING.md, docs/releasing.md, version/version.go
=> chore: releasing version 0.17.0

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 0.18.0

config/config.go
Added boostrap node in the config
=> feat: adding jwmdev bootstrap node to config

network/mdns_test.go
This PR will fix the MDNS test issue caused by updating the libp2p version.
=> test(mdns): fix MDNS test issue

util/errors/errors.go, wallet/vault/errors.go, wallet/vault/vault.go, wallet/vault/vault_test.go, wallet/wallet.go, wallet/wallet_test.go
Implementation of [PIP-13](https://pips.pactus.org/PIPs/pip-13)
=> feat: implement pip-13

network/network.go
This PR disables the Ping protocol in LibP2P.
=> fix: disabling libp2p ping protocol

wallet/servers.json
This PR adds more servers for wallet. 
TODO:
For offline commands like set labels, we should not connect to any server. Issue #850
=> chore: adding more servers for wallet

network/utils.go, sync/firewall/firewall.go, sync/sync.go
Reducing the warning level of certain logs to debug level, reporting non-critical errors for the network.
=> chore: updating some log levels

CHANGELOG.md, config/example_config.toml, docs/releasing.md, util/logger/config.go, version/version.go
=> chore: releasing version 0.18.0

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 0.19.0

CHANGELOG.md, docs/patching.md, util/logger/logger.go
=> chore: releasing version 0.18.1

docs/patching.md, docs/releasing.md
This PR updates the releasing document.
=> chore: updating the releasing documents

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 0.18.2

.github/releasers/pactus_downloader.sh, Dockerfile, cmd/cmd.go, cmd/daemon/init.go, cmd/daemon/start.go, cmd/gtk/main.go, cmd/wallet/main.go, network/utils.go, sync/sync.go
This PR updates the Dockerfile and downloader scrip.
- Fixing #872
=> chore: updating Dockerfile and downloader script

CHANGELOG.md, docs/patching.md, version/version.go
=> chore: releasing version 0.18.2

cmd/daemon/start.go, go.mod, go.sum
Referenced this https://github.com/pactus-project/pactus/pull/855#issuecomment-1867283627
- Fixes #805
/claim #805
=> feat: check already running by lock file

docs/patching.md, docs/releasing.md
Proofreading and updating the releasing documents
=> chore: updating the releasing docs

consensus/cp.go, consensus/cp_decide.go, consensus/cp_mainvote.go
Check voteset for strong termination in change proposer phase.
=> fix(consensus): check voteset for CP strong termination

CHANGELOG.md
=> chore: releasing version 0.18.3

docs/patching.md, version/version.go
=> chore: bumping version to 0.18.4

config/config.go
=> chore: removing jwmdev bootstrap node from config

consensus/consensus.go, consensus/propose.go, state/execution_test.go, state/facade.go, state/mock.go, state/state.go, state/state_test.go, state/validation.go, state/validation_test.go, store/block_test.go, util/testsuite/testsuite.go
This PR refactors the state tests and clean them ;)
=> test: refactoring state tests

network/gossip.go
This PR refines the PubSub params for Gossip nodes.
=> chore(network): refining GossipSubParams for Gossiper node

network/gater.go, network/peermgr.go, network/relay_service.go, network/utils.go
Close connection with the relay node for the public nodes
=> fix(network): close relay connection for public node

network/gossip.go
This PR disable GossipSub and starts FloodSub.
=> feat(network): disabling gosipsub, only floodsub

CHANGELOG.md, version/version.go
=> chore: releasing version 0.18.4

consensus/consensus_test.go, consensus/propose.go, network/relay_service.go, state/facade.go, state/mock.go, state/score/score.go, state/score/score_test.go, state/state.go
This PR implements the [PIP-19](https://pips.pactus.org/PIPs/pip-19)
=> feat: implementing pip-19

CHANGELOG.md, consensus/propose.go, docs/releasing.md, version/version.go
=> chore: releasing version 0.19.0

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 0.20.0

network/network_test.go
This PR fixes a random test failure for TestMDNS.
=> test(network): fixing random mDNS test failure

www/grpc/buf/grpc-gateway.config.yaml, www/grpc/gen/go/transaction.pb.gw.go, www/grpc/swagger-ui/pactus.swagger.json
This PR will add some missing APIs to the gRPC gateway.
=> fix(gRPC): adding missing get raw transaction APIs to gRPC gateway

network/notifee.go
This PR adds the remote address to a log in NotifeeService.
=> chore(network): updating NotifeeService logs

CHANGELOG.md, version/version.go
=> chore: releasing version 0.20.0

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 0.21.0

CHANGELOG.md, version/version.go
=> chore: releasing version 0.20.1

docs/patching.md, version/version.go
=> chore: bumping version to 0.20.2

CONTRIBUTING.md
This PR updates the contributing document.
=> chore: updating contributing doc

config/config.go, config/config_test.go, config/example_config.toml, wallet/servers.json
This PR adds official bootstrap nodes for the Mainnet 🍀
=> chore(config): adding bootstrap nodes

docs/bootstrap.md
This pull request adds guidelines for bootstrap nodes to add their node into the Pactus project.
=> chore: add bootstrap node guideline

config/bootstrap.json
Addition of bootstrap node for Mr. HoDL.
=> chore: adding MrHodl bootstrap nodes

.github/releasers/macos/gui.bundle, .github/releasers/releaser_gui_macos.sh, .github/workflows/releaser.yml
This PR releases GUI for macOS ARM (Like M1 and M2).
Fixes #372
=> chore: add release for macOS ARM using self-hosted runner

docs/bootstrap.md
This PR add recommenced configs for the bootstrap node.
=> docs(bootstrap): adding recommended config

config/bootstrap.json
=> chore: adding JohnVNBnode bootstrap nodes

config/bootstrap.json
Add LVTNode as a community bootstrap node
=> chore: add bootstrap address for LVTNode

config/bootstrap.json
adding SGTstake Bootstrap Node.
=> chore: adding SGTstake Bootstrap Node

config/bootstrap.json
adding KarmaNodes Bootstrap Node
=> chore: add KarmaNodes Bootstrap Node

config/bootstrap.json
adding Stake.Works Bootstrap Node
=> chore: add Stake.Works Bootstrap Node

config/bootstrap.json
=> chore: add kenz Bootstrap Node

config/bootstrap.json
Adding Validator247 Bootstrap Node
=> chore: add Validator247 Bootstrap Node 

config/bootstrap.json
add bootstrap address for jackieluong
=> chore: add bootstrap address for jackieluong

config/bootstrap.json
Adding MoneyLow-VNBnode Bootstrap Node
=> chore: add MoneyLow-VNBnode Bootstrap Node

config/bootstrap.json
Adding bootstrap address for alishiaplowden
=> chore: add bootstrap address for alishiaplowden

config/bootstrap.json
=> chore: add CherryValidator Bootstrap Node

config/bootstrap.json
Adding bootstrap address for diszell2008
=> chore: add bootstrap address for diszell2008

config/bootstrap.json
Adding bootstrap address for tiantsi
=> chore: add bootstrap address for tiantsi

config/bootstrap.json
Adding bootstrap address for vinhhathacha
=> chore: add bootstrap address for vinhhathacha

config/bootstrap.json
Adding CodeBlockLabs Bootstrap Address
=> chore: add bootstrap address for CodeBlockLabs 

config/bootstrap.json
Adding bootstrap address for 0xSown
=> chore: add bootstrap address for 0xSown

config/bootstrap.json
=> chore: add bootstrap address for Adora

config/bootstrap.json
Adding bootstrap address for Node39
=> chore: add bootstrap address for Node39

config/bootstrap.json
Adding bootstrap node for sebus
=> chore: add bootstrap node for sebus

config/bootstrap.json
Updating Bootstrap info for BearValidator
=> chore: update bootstrap info for BearValidator

config/bootstrap.json
Adding bootstrap address for Stilucky.
=> chore: add bootstrap address for Stilucky

config/bootstrap.json
Adding bootstrap address for Toncatuyvu
=> chore: add bootstrap address for Toncatuyvu

config/bootstrap.json
Adding bootstrap address for Wanderersg
=> chore: add bootstrap address for Wanderersg

config/bootstrap.json
add `p10node` to bootstrap node
=> chore: add bootstrap address for p10node

config/bootstrap.json
This PR adds bootstrap node for dragon
=> chore: add bootstrap node for dragon

CHANGELOG.md, docs/releasing.md, version/version.go
=> chore: releasing version 1.0.0

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 1.1.0

Makefile, www/grpc/buf/buf.gen.yaml, www/grpc/gen/docs/index.html, www/grpc/gen/docs/index.md
Implement documentation for proto files
=> feat: generate documentation for proto files

config/bootstrap.json
Adding bootstrap address for bettevinup
=> chore: add bootstrap address for bettevinup

.github/workflows/releaser.yml
This PR adds checksum for macOS-ARM binaries.
=> ci: add checksum for macos-arm binaries

network/network.go, util/logger/logger.go
This PR addresses random test failures in network tests during race condition checks. 
An example of this failure: https://github.com/pactus-project/pactus/actions/runs/7775759720/job/21202090904?pr=1055
=> test: prevent random failure on race test

www/grpc/buf/buf.gen.yaml, www/grpc/buf/website.tmpl, www/grpc/gen/docs/website.md
This PR adds a template to generate document for gRPC for https://pactus.org/
=> docs: add template to generate grpc document for website

config/bootstrap.json
Adding bootstrap address for 5t0q6pr
=> chore: add bootstrap address for 5t0q6pr

config/bootstrap.json
Adding bootstrap address for SumNode
=> chore: add bootstrap address for SumNode

config/bootstrap.json
Adding bootstrap address for 00PactucValidator32
=> chore: add bootstrap address for 00PactucValidator32

config/bootstrap.json
Adding bootstrap address for VALIDATOR.WIKI
=> chore: add bootstrap address for VALIDATOR.WIKI

config/bootstrap.json
Adding bootstrap address for anpjwq
=> chore: add bootstrap address for anpjwq

config/bootstrap.json
Adding bootstrap address for Vozer
=> chore: add bootstrap address for Vozer

network/peermgr.go, network/utils.go, sync/handler_block_announce.go, sync/handler_blocks_response.go, sync/handler_blocks_response_test.go, sync/peerset/peer_set.go, sync/peerset/status_code.go, sync/sync.go, sync/sync_test.go, tests/main_test.go
This PR improves the syncing process and reduces outbound connections for better connectivity.
=> fix(sync): improve syncing process

config/bootstrap.json
Adding bootstrap address for Khacbao
=> chore: add bootstrap address for Khacbao

docs/patching.md, version/version.go
This PR updates the patch version and patching document.
=> chore: update version and patching doc

CHANGELOG.md, config/bootstrap.json
=> chore: releasing version 1.0.1

.golangci.yml, network/network.go, sync/sync.go, wallet/client.go, wallet/wallet.go, wallet/wallet_test.go, www/grpc/server.go, www/http/blockchain.go, www/http/network.go, www/http/server.go, www/http/transaction.go, www/nanomsg/server.go
This PR enables contextcheck linter as explained here: https://pkg.go.dev/github.com/sylvia7788/contextcheck
- Fixes #1100
=> chore: enable contextcheck linter

config/bootstrap.json
Adding bootstrap address for catsmile100
=> chore: add bootstrap address for catsmile100

config/bootstrap.json
Adding bootstrap address for Winnode
=> chore: add bootstrap address for Winnode

config/bootstrap.json
Adding bootstrap address for F2Node
=> chore: add bootstrap address for F2Node

config/example_config.toml, util/logger/config.go, util/logger/logger.go
=> feat(logger): adding file_only option

www/grpc/buf/grpc-gateway.config.yaml, www/grpc/gen/go/wallet.pb.gw.go, www/grpc/swagger-ui/pactus.swagger.json
=> fix(gRPC): adding sign raw transaction API to gateway

config/example_config.toml, util/logger/config.go, util/logger/logger.go
=> feat(logger): adding log target

config/bootstrap.json
Adding bootstrap address for Sipannachi
=> chore: add bootstrap address for Sipannachi

CHANGELOG.md, config/bootstrap.json, version/version.go
=> chore: releasing version 1.0.2

config/bootstrap.json
Adding bootstrap address for JackieLuong135
=> chore: add bootstrap address for JackieLuong135

config/bootstrap.json
Adding bootstrap address for Lisachoake
=> chore: add bootstrap address for Lisachoake

network/network.go, sync/sync.go, www/grpc/server.go, www/http/server.go, www/nanomsg/server.go
Refactor cancellation token from `func()` to `cancel func type`
=> refactor: change func() to cancel func type

config/bootstrap.json
Adding bootstrap address for hainguyen0094_22439
=> chore: add bootstrap address for hainguyen0094_22439

cmd/ctl/cmd/root.go
=> chore: remove toggle command

config/config.go, config/config_test.go
This PR updates the localnet configuration. 
It helps connecting two local nodes with the same genesis using the MDNS protocol.
=> chore: updating localnet config

config/config.go, genesis/genesis_test.go, genesis/testnet.json, wallet/servers.json
This PR define the genesis file for the permanent Testnet.
=> feat(testnet): define permanent Testent genesis

wallet/servers.json
Updating Testnet servers for wallet command
=> chore: update testnet servers

network/peermgr.go, node/node.go, sync/handler_blocks_request.go, sync/sync.go, sync/sync_test.go, tests/main_test.go
This PR fixes a random test failure, specially when the streams get closed and test nodes get isolated.
=> test: fix system test random failure

config/bootstrap.json
add Dezh tech bootstrap node 1
=> chore(config): addition of  Dezh tech bootstrap node 1

docs/update-dependensies.md
In this PR I added a document that is a guide to how to update this repository dependencies.
This guide is useful for any time we need to update our dependencies, mostly before new releases.
=> docs: adding update dependencies documentation

network/interface.go, network/notifee.go, network/peermgr.go, sync/handler_blocks_response.go, sync/handler_hello.go, sync/peerset/peer.go, sync/peerset/peer_set.go, sync/peerset/peer_set_test.go, sync/peerset/peer_test.go, sync/peerset/service/services.go, sync/peerset/service/services_test.go, sync/sync.go, sync/sync_test.go, www/grpc/network.go
This PR refactors sync and improve syncing process.
=> refactor(sync): improve syncing process

cmd/gtk/main.go, cmd/wallet/main.go, wallet/client.go, wallet/wallet.go, wallet/wallet_test.go
This PR fixes the wallet connection issue that cause panic on wallet commands.
=> fix(wallet): fix wallet conn issue

.github/releasers/releaser_cli.sh, .github/releasers/releaser_gui_linux.sh, .github/releasers/releaser_gui_macos.sh, .github/releasers/releaser_gui_windows.sh, Dockerfile
This PR includes `pactus-shell` in the releaser
=> build(releaser): include pactus-shell into releaser

cmd/gtk/main_window.go
##Description
This PR updates block explorer link to https://pacviewer.com/
=> chore(GUI): change blockchain explorer link

www/grpc/buf/openapi.config.yaml, www/grpc/swagger-ui/pactus.swagger.json
This PR simply adds Basic authentication information to the HTTP Header.
=> fix(gRPC): add basic auth option in header

CHANGELOG.md, version/version.go
=> chore: releasing version 1.1.0

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 1.2.0

CHANGELOG.md, version/version.go
=> chore: releasing version 1.1.1

docs/patching.md, version/version.go
=> chore: bumping version to 1.1.2

www/grpc/wallet.go
We have to save wallet once we make writes and change the data of wallet file.
=> fix(wallet): saving wallet file after generating new address in gRPC

CHANGELOG.md
=> chore: releasing version 1.1.2

CHANGELOG.md, version/version.go
=> chore: releasing version 1.1.3

sandbox/sandbox.go
This PR increases the block height that apply the banned list to 82,000.
=> chore: increase block height to apply banned list

docs/patching.md, version/version.go
=> chore: bumping version to 1.1.4

www/http/transaction.go
=> fix(HTTP): using amount type for fee in transaction details

sync/handler_hello.go, sync/handler_hello_test.go, sync/peerset/peer_set.go, sync/peerset/peer_set_test.go, sync/peerset/session/manager.go, sync/peerset/session/stats.go
This PR introduces the session manager to manage download sessions.
=> fix(sync): introduce session manager

CHANGELOG.md, version/version.go
=> chore: releasing version 1.1.4

network/network.go, network/utils.go
=> chore: releasing version 1.1.4 (RC2)

docs/patching.md, version/version.go
=> chore: bumping version to 1.1.5

state/state.go
This PR removes an unnecessary log in state for availability score.
=> chore: remove unnecessary log in state for availability score

config/example_config.toml, network/config.go, network/gossip.go, network/network_test.go, network/ratelimit.go, network/ratelimit_test.go
This PR defines a config for rate limit threshold.
=> feat(network): define config for rate limit threshold

CHANGELOG.md, version/version.go
=> chore: releasing version 1.1.5

config/example_config.toml, execution/errors.go, execution/execution.go, execution/execution_test.go, execution/executor/bond_test.go, execution/executor/transfer_test.go, network/ratelimit.go, node/node.go, state/mock.go, state/state.go, state/state_test.go, tests/main_test.go, tests/transaction_test.go, txpool/config.go, txpool/config_test.go, txpool/interface.go, txpool/mock.go, txpool/pool.go, txpool/txpool.go, txpool/txpool_test.go, types/param/param.go, types/tx/tx.go, www/grpc/transaction_test.go
This PR introduces dynamic transaction fees. The fee increases when the transaction pool becomes full.
=> feat: add dynamic fee

CHANGELOG.md, version/version.go
=> chore: releasing version 1.1.6

config/config_test.go, config/example_config.toml, sync/firewall/config.go, sync/firewall/firewall.go, sync/firewall/firewall_test.go, sync/sync.go, sync/sync_test.go, util/addr/addr.go, util/addr/addr_test.go
This PR fix some issues related to #1298
=> fix(sync): load black listed addresses from the config

CHANGELOG.md, version/version.go
=> chore: releasing version 1.1.7

consensus/interface.go, consensus/manager.go, network/gossip_test.go, sync/bundle/message/hello_ack.go, sync/config.go, sync/handler_query_proposal.go, sync/handler_query_proposal_test.go, sync/handler_query_votes.go, sync/handler_query_votes_test.go
This PR defines a rate limit for query vote and proposal messages.
=> fix(sync): define rate limit for query vote and proposal

consensus/config.go, consensus/consensus_test.go, consensus/cp_prevote.go, genesis/genesis_test.go, state/state.go, state/state_test.go, sync/peerset/peer_set_test.go, util/time.go, util/time_test.go
This PR reduces the change prosper timeout to 6 seconds.
=> fix(consensus): reduce ChangeProposerTimeout to 6 seconds

cmd/gtk/dialog_transaction_unbond.go, cmd/gtk/dialog_transaction_withdraw.go, config/example_config.toml, state/state.go, txpool/config.go, txpool/config_test.go, txpool/pool.go, txpool/txpool.go, txpool/txpool_test.go
This PR sets a fixed fee of 0.1 PAC for transactions to avoid spam transactions. 
This fee will be replaced by a dynamic fee in future releases.
=> fix: set fix fee 0.1 PAC for transactions

CHANGELOG.md, version/version.go
=> chore: releasing version 1.1.8

www/grpc/middleware.go, www/grpc/middleware_test.go, www/grpc/server.go
Add stacktrace to locate panic
=> fix(grpc): add stacktrace to locate panic

sync/handler_hello.go, www/grpc/network.go, www/http/network.go, www/http/server.go
This PR adds connections info and clock-offset to the node-info API in HTTP module.
=> fix(HTTP): add clock offset and connection info to node-info API

sync/config.go
Update latest version support to 1.1.8
- Fixes #1326
=> fix(sync): update latest supporting version

sync/sync.go
Add `IsBannedAddress` in processing the connect event.
=> fix(sync): add IsBannedAddress check in processing connect event

config/example_config.toml, txpool/config.go, txpool/config_test.go
This PR makes minimum fee configurable.
=> feat(config): make minimum fee configurable

wallet/vault/vault.go
Set public key on response get new address
- Fixes #1346
=> fix(wallet): add public key on get new address

wallet/vault/vault_test.go, www/grpc/wallet_test.go
This PR updates tests for the `GetNewAddress` APIs and ensures the Public Key is set.
=> test(wallet): update tests for GetNewAddress API

go.mod, go.sum
Jrpc send all client headers make stream issue for gRPC, currently just send custom headers for gRPC.
https://github.com/PacViewer/jrpc-gateway/compare/v0.3.2...v0.4.0
=> chore(jrpc): update jrpc gateway to v0.4.0 to fix header issue

CHANGELOG.md, version/version.go
=> chore: releasing version 1.2.0

docs/patching.md, docs/releasing.md, version/version.go
=> chore: bumping version to 1.3.0

cmd/gtk/widget_node.go, sync/interface.go, sync/mock.go, sync/sync.go, util/errors/errors.go, util/ntp/ntp.go, util/ntp/ntp_test.go, util/ntp/query.go, www/grpc/network.go
This PR adds test for NTP checker and fixes "-0 seconds" issue on GUI.
=> test(ntp): add tests for NTP Checker

config/bootstrap.json
I reinstalled my node and my Peers ID changed. I updated my Peers ID
=> chore: update bootstrap.json

version/version.go
=> chore: bumping version to 1.2.1

docs/patching.md, docs/releasing.md
This PR updates the releasing and patching documents.
=> chore: update releasing doc

docs/patching.md, docs/releasing.md, docs/update-dependensies.md, version/version.go
=> chore: bumping version to 1.4.0

consensus/consensus.go, consensus/consensus_test.go, consensus/propose_test.go, sandbox/sandbox_test.go, state/execution_test.go, state/lastinfo/last_info_test.go, state/mock.go, state/score/score_test.go, state/state_test.go, state/validation_test.go, sync/bundle/message/block_announce_test.go, sync/bundle/message/blocks_response_test.go, sync/bundle/message/transactions_test.go, sync/handler_block_announce_test.go, sync/handler_blocks_response_test.go, sync/handler_transactions_test.go, txpool/mock.go, txpool/txpool_test.go, types/block/block_test.go, types/block/txs_test.go, types/certificate/block_certificate.go, types/certificate/block_certificate_test.go, types/certificate/certificate.go, types/certificate/certificate_test.go, types/certificate/vote_certificate.go, types/certificate/vote_certificate_test.go, types/tx/tx_test.go, util/testsuite/testsuite.go, wallet/history_test.go, www/grpc/transaction_test.go
This PR refactors the testsuite and adds transaction and block maker to the testsuite.
=> test: add transaction and block makers to testsuite

cmd/daemon/prune.go
This PR disables logger on running prune command.
=> chore: disable logger on prune command

version/version_test.go
This PR ensures the current version string is valid and parable.
=> test(version): check if the current version is parsable

.github/releasers/macos/Info.plist, .github/releasers/macos/gtk3-launcher.sh, .github/releasers/macos/gui.bundle, .github/releasers/macos/run-install-name-tool-change.sh, .github/releasers/releaser_gui_macos.sh, .github/workflows/releaser.yml, cmd/gtk/assets/ui/main_window.ui, cmd/gtk/main_window.go
fix running the macOS on arm64 and amd64
=> build(gtk): fix macOS issue

CHANGELOG.md, docs/releasing.md, version/version.go
=> chore(release): releasing version 1.4.0

.github/releasers/releaser_gui_macos.sh, .github/workflows/semantic-pr.yml
Make sure macOS launcher is executable.
=> build(macos): set launcher as executable

docs/patching.md, docs/releasing.md, version/version.go
=> chore(version): bumping version to 1.5.0

cmd/gtk/assets/ui/widget_node.ui, cmd/gtk/widget_node.go
With this feature GUI users can determine the type of node that they are running...
=> feat(gtk): adding IsPrune to node widget

CONTRIBUTING.md, docs/gtk-gui-development.md
I was adding some changes to GUI and I found that for the development of GUI, we have some requirements and details that devs need to know. Personally sometimes I forget them. So I decided to write a short guide which can help devs to setup their machine can work on GUI in a proper way.
=> docs(gtk): adding GTK GUI development guide

Makefile, www/grpc/buf/grpc-md.tmpl, www/grpc/buf/json-rpc-md.tmpl, www/grpc/gen/docs/grpc.md, www/grpc/gen/docs/json-rpc.md, www/grpc/gen/go/wallet.pb.go, www/grpc/gen/java/pactus/wallet/WalletOuterClass.java, www/grpc/gen/rust/pactus.rs, www/grpc/proto/wallet.proto, www/grpc/swagger-ui/pactus.swagger.json
This PR change the enum type to numeric for JSON-RPC documentation.
=> fix(grpc): change enum type to numeric for documentation

cmd/wallet/address.go, crypto/public_key.go, execution/execution.go, execution/execution_test.go, sandbox/interface.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, state/execution_test.go, state/state_test.go, store/block.go, store/interface.go, store/mock.go, store/store.go, store/store_test.go, store/tx.go, sync/handler_blocks_response_test.go, types/tx/tx_test.go, util/testsuite/testsuite.go
The store can now cache Ed25519 public keys. This way we are almost ready to enable Ed25519 for the Testnet.
=> fix(store): cache Ed25519 Public Keys

crypto/bls/bls_bench_test.go
Add benchmark test with allocation report for bls package.
=> chore(crypto): add benchmark for bls package

store/store.go, store/tx.go, www/grpc/blockchain_test.go
Simple update on HTTP test for the consensus-info.
=> test(http): update http/consensus-info test

sync/bundle/bundle.go, sync/sync.go
This PR fixes an issue where the stream did not close on error.
=> fix(sync): close stream on read error

config/config.go
This PR adds new node as bootstrap node for the Testnet. The rest of the nodes should be updated.
=> chore(config): update bootstrap nodes for Testnet

CHANGELOG.md, version/version.go
=> chore(release): releasing version 1.5.0

docs/releasing.md, version/version.go
=> chore(version): bumping version to 1.6.0

util/encoding/encoding_test.go
This PR adds a random test for `VarInt`.
=> test(util): add random test for var int

config/example_config.toml, tests/main_test.go, txpool/config.go, txpool/config_test.go, txpool/txpool_test.go
In this PR new fee model (consumption fee) configs added.
- Fixes #1541
=> feat(config): add consumption fee configs

www/grpc/buf/json-rpc-md.tmpl, www/grpc/gen/docs/json-rpc.md, www/grpc/gen/go/wallet.cobra.pb.go, www/grpc/gen/go/wallet.pb.go, www/grpc/gen/go/wallet.pb.gw.go, www/grpc/gen/go/wallet_grpc.pb.go
This PR changes gRPC to JSON-RPC in doc.
I'm working on fixing OneOf issue in doc.
- Fixes #1551
=> docs(jsonrpc): change grpc to json-rpc for doc template

util/io_test.go
This PR updates the `TestListFilesInDir` test and add directory to the test.
=> chore(util): update TestListFilesInDir test

util/io_test.go
Remove hidden dot for public file
https://github.com/pactus-project/pactus/pull/1563#pullrequestreview-2380989165
=> test(util): remove hidden dot for public file

cmd/gtk/assets/ui/dialog_transaction_bond.ui, cmd/gtk/assets/ui/dialog_transaction_transfer.ui, cmd/gtk/assets/ui/dialog_transaction_withdraw.ui, cmd/gtk/dialog_transaction_bond.go, cmd/gtk/dialog_transaction_transfer.go, cmd/gtk/dialog_transaction_withdraw.go, cmd/gtk/utils.go
Add fee entry for transfer, bond and withdraw.
- Fixes #1573
=> feat(gtk): add fee entry for transfer, bond and withdraw

.github/workflows/coverage.yml
Fix coverage test on PR and upload report
=> ci(github): update coverage action version

.github/releasers/releaser_cli.sh
Add android build
- Fixes #1506
=> chore(release): add android build

docs/patching.md, docs/releasing.md, version/version.go
=> chore(version): bumping version to 1.7.0

CHANGELOG.md, version/version.go
=> chore(release): releasing version 1.6.1

.github/releasers/releaser_gui_windows.sh
This PR adds libsharpyuv-0.dll to Windows installer.
=> ci(release): add libsharpyuv-0.dll to the Windows installer

CHANGELOG.md, docs/patching.md, version/version.go
=> chore(release): releasing version 1.6.2

docs/patching.md, version/version.go
=> chore(version): bumping version to 1.6.3

CHANGELOG.md
=> chore(release): releasing version 1.6.3

docs/patching.md, version/version.go
=> chore(version): bumping version to 1.6.4

.github/workflows/semantic-pr.yml, config/example_config.toml, sync/firewall/config.go, sync/firewall/firewall.go
This PR updates firewall to detect consensus height and set the default rate-limit for block topic to 1.
=> chore(firewall): update firewall

CHANGELOG.md, version/version.go
=> chore(release): releasing version 1.6.4

docs/patching.md, version/version.go
=> chore(version): bumping version to 1.6.5

network/gossip.go
Restore default message queue size in PubSub module
=> fix(network): restore default message queue size in PubSub module

CONTRIBUTING.md
Correct quotation style in document
=> chore(docs): correct quotation style in text

www/zmq/publisher.go, www/zmq/publisher_tx_info.go, www/zmq/publisher_tx_info_test.go
Add publisher transaction info
- Fixes #1659
=> feat(zeromq): add publisher transaction info

docs/patching.md, version/version.go
=> chore(version): bumping version to 1.8.0

config/bootstrap.json
Adding bootstrap address for korcano
=> chore(config): add bootstrap address for korcano

cmd/wallet/main.go, cmd/wallet/neuter.go, wallet/store.go, wallet/wallet.go
Add Neuter command for wallet
- Fixes #1661
=> feat(wallet-cmd): add Neuter command for wallet

state/state.go
add comments to checkXeggexState function
=> chore(state): add comments to checkXeggexState function

CHANGELOG.md, version/version.go
=> chore(release): releasing version 1.7.1

docs/patching.md, version/version.go
=> chore(version): bumping version to 1.7.2

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This PR updates the GitHub's Issue and Pull Request templates.
=> chore(github): update issue and PR templates

.github/workflows/codeql.yml
This PR sets up CodeQL action for Go Language and actions.
=> ci(github): add GitHub CodeQL Action

.github/workflows/codeql.yml, .github/workflows/coverage.yml, .github/workflows/deadlock.yml, .github/workflows/docker.yml, .github/workflows/gui.yml, .github/workflows/linting.yml, .github/workflows/packager.yml, .github/workflows/releaser.yml, .github/workflows/semantic-pr.yml, .github/workflows/testing.yml
To make building and Testing GUI faster, this PR caches the go packages.
Fixes #1462
=> ci(github): cache the Go dependencies for GUI build

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/packager/js/index.js, .github/packager/js/package.json, .github/packager/packager.sh, .github/packager/python/pactus_grpc/__init__.py, .github/packager/python/pactus_grpc/__init__.pyi, .github/packager/python/setup.py, .github/releasers/releaser_cli.sh, .github/releasers/releaser_gui_linux.sh, .github/releasers/releaser_gui_macos.sh, .github/releasers/releaser_gui_windows.sh, .github/workflows/codeql.yml, .github/workflows/coverage.yml, .github/workflows/deadlock.yml, .github/workflows/docker.yml, .github/workflows/gui.yml, .github/workflows/linting.yml, .github/workflows/packager.yml, .github/workflows/releaser.yml, .github/workflows/semantic-pr.yml, .github/workflows/testing.yml, .gitignore
This PR adds Packager to version 1.7.2
=> feat(other): add packager

CHANGELOG.md, version/version.go
=> chore(release): releasing version 1.7.2

.github/packager/packager.sh, .github/workflows/packager.yml
The ref set to `main` if we have a git tag. This PR aims to fix this issue.
=> chore(github): fix ref issue on checkout action

docs/patching.md, version/version.go
=> chore(version): bumping version to 1.7.3

.github/packager/js/package.json, .github/packager/python/setup.py, www/grpc/buf/buf.gen.yaml, www/grpc/gen/js/blockchain_grpc_pb.js, www/grpc/gen/js/network_grpc_pb.js, www/grpc/gen/js/transaction_grpc_pb.js, www/grpc/gen/js/utils_grpc_pb.js, www/grpc/gen/js/wallet_grpc_pb.js
Fix gRPC deprecated dependency issue. Look #1750
=> fix(grpc): update gRPC client to use @grpc/grpc-js

CHANGELOG.md, version/version.go
=> chore(release): releasing version 1.7.3

docs/patching.md, version/version.go
=> chore(version): bumping version to 1.7.4

config/example_config.toml, www/grpc/buf/openapi.config.yaml, www/grpc/server.go, www/http/server.go, www/jsonrpc/server.go, www/rest/config.go, www/rest/config_test.go, www/rest/rest.go, www/rest/swagger-ui/pactus.swagger.json
This PR defines the base_path for the REST APIs and allows users to customize it.
=> feat(rest): define base path for REST APIs

scripts/snapshot.py
Currently, snapshot supports managing the daemon service via a `systemd` unit. This PR adds support for `systemctl` and Docker Compose services to retrieve snapshots.
=> chore(scripts): support docker compose service for snapshot

.github/packager/js/grpc/package.json, .github/packager/js/jsonrpc/package.json, .github/packager/packager.sh, .github/workflows/packager.yml, www/grpc/buf/openrpc.tmpl, www/grpc/gen/open-rpc/pactus-openrpc.json
> This PR add package generator for jsonrpc
=> feat(release): add packager jsonrpc for javascript

CHANGELOG.md, version/version.go
=> chore(release): releasing version 1.7.4

docs/patching.md, version/version.go
=> chore(version): bumping version to 1.7.5

execution/executor/batch_transfer_test.go
This PR covered Batch Transfer Executor with tests.
Fixes #1789
=> test(execution): add tests for batch transfer

.github/releasers/releaser_gui_macos.sh, execution/errors.go, execution/execution.go, execution/execution_test.go, txpool/txpool_test.go, util/testsuite/testsuite.go
This PR sets the Batch Transfer Height to 4,800,000 based on [PIP-39](https://pips.pactus.org/PIPs/pip-39)
=> fix(execution): set batch transfer height

execution/execution.go, sandbox/interface.go, sandbox/mock.go, sandbox/sandbox.go, sandbox/sandbox_test.go, state/state.go
This PR checks the network for the Batch Transfer payloads.
=> fix(execution): check network type for batch transfer

sync/firewall/firewall.go
This PR changes the log level to debug.
=> chore(sync): change log level to debug

docs/release-candidate.md
Adding Release-Candidate Document.
=> docs(releaser): add Release-Candidate doc

.github/workflows/semantic-pr.yml, Dockerfile
Fix the Dockerfile linting issue
=> chore(other): fix Dockerfile linting issue

sync/handler_blocks_response_test.go, util/bech32m/bech32m.go, wallet/client.go
=> chore(other): fix some comments

CHANGELOG.md, docs/releasing.md, version/version.json
=> chore(release): releasing version 1.8.0

Dockerfile
Update Go version in Dockerfile
=> refactor(docker): update go version for Dockerfile

cmd/wallet/address.go
This PR adds `label` option for new address command
=> feat(cmd): add label option for new address command

wallet/store.go
This PR fixes an issue on upgrading old Testnet wallets.
=> fix(wallet): set Testnet network on upgrading wallet

consensus/propose.go, state/execution.go, state/execution_test.go
This PR checks the foundation address in Subsidy transaction.
=> fix(state): check foundation address in subsidy transaction

.github/workflows/gui.yml
Removes `restore-keys` for cached items.
=> ci(github): set step ID for cache step

docs/patching.md, docs/releasing.md, version/version.json
=> chore(version): bumping version to 1.10.0

www/grpc/buf/grpc.md.tmpl, www/grpc/buf/json-rpc.md.tmpl, www/grpc/gen/docs/grpc.md, www/grpc/gen/docs/json-rpc.md
This PR  updates the API documents
=> chore(grpc): update API docs

docs/patching.md, version/version.json
=> chore(version): bumping version to 1.9.2

consensusv2/consensus_test.go
This PR fix a random data-race issue in consensus-v2 tests.
=> test(consensus): fix data-race issue on consensus tests

state/state.go
This PR checks if we are at the genesis height by verifying the certificate. Only the genesis block has no certificate.
=> refactor(state): check genesis state using certificate presence

execution/execution_test.go, state/execution.go, state/execution_test.go, state/lastinfo/last_info_test.go, state/param/param.go, state/state.go, state/state_test.go, state/validation_test.go, store/mock.go, store/store_test.go, sync/handler_blocks_response_test.go, txpool/txpool_test.go, types/block/block_test.go, types/block/txs.go, types/block/txs_test.go, types/tx/factory.go, types/tx/tx_test.go, util/testsuite/testsuite.go, wallet/wallet_test.go, www/grpc/blockchain_test.go, www/html/blockchain_test.go, www/html/transaction_test.go
This PR refactor reward transaction logic and remove the legacy checks as they are obsoleted.
=> refactor(state): refactor reward transaction

sync/bundle/bundle.go, sync/bundle/bundle_test.go, sync/handler_blocks_request_test.go, sync/handler_blocks_response_test.go, sync/sync_test.go
This PR defines limit for the size of elements in array and map in CBOR decoder.
=> fix(cbor): set limit for Map and Array in CBOR decoder

.github/packager/packager.sh, .github/packager/rust/grpc/Cargo.toml, .github/packager/rust/grpc/src/lib.rs
This PR adds the rust-grpc package.
=> feat(packager): add rust-grpc package

.github/packager/js/grpc/README.md, .github/packager/js/jsonrpc/README.md, .github/packager/packager.sh, .github/packager/python/grpc/README.md, .github/packager/python/jsonrpc/README.md, .github/packager/rust/grpc/README.md, .github/packager/rust/grpc/src/lib.rs, .github/packager/rust/jsonrpc/README.md, .github/packager/rust/jsonrpc/src/lib.rs, .github/workflows/packager.yml
This PR publishes both gRPC and JSON-RPC packages for Rust Language.
Fixes #1911 #1727
=> chore(packager): publish rust packages

CHANGELOG.md, version/version.json
=> chore(release): releasing version 1.9.2

docs/patching.md, version/version.json
=> chore(version): bumping version to 1.9.3

.github/packager/rust/jsonrpc/Cargo.toml, .github/packager/rust/jsonrpc/README.md, .github/packager/rust/jsonrpc/src/lib.rs, .github/workflows/packager.yml, CHANGELOG.md, version/version.json, www/grpc/buf/openrpc.tmpl, www/grpc/gen/dart/transaction.pb.dart, www/grpc/gen/docs/grpc.md, www/grpc/gen/docs/json-rpc.md, www/grpc/gen/go/transaction.cobra.pb.go, www/grpc/gen/go/transaction.pb.go, www/grpc/gen/java/pactus/TransactionOuterClass.java, www/grpc/gen/open-rpc/pactus-openrpc.json, www/grpc/gen/rust/pactus.rs, www/grpc/proto/transaction.proto, www/http/swagger-ui/pactus.swagger.json
=> chore(release): releasing version 1.9.4

docs/patching.md, version/version.json
=> chore(version): bumping version to 1.9.5
